<script setup>
import { computed, onBeforeUnmount, reactive, ref, watch } from 'vue';
import { Link, router, useForm } from '@inertiajs/vue3';
import axios from 'axios';
import { BellAlertIcon, EnvelopeIcon, ChatBubbleLeftIcon, ClockIcon, ArrowRightIcon, ChevronRightIcon, ShieldCheckIcon, ExclamationTriangleIcon, ArrowPathIcon, CheckCircleIcon } from '@heroicons/vue/24/outline';
import AppButton from '@/Components/Product/AppButton.vue';
import AppDialog from '@/Components/Product/AppDialog.vue';
import FieldError from '@/Components/Product/FieldError.vue';
import PageHeader from '@/Components/Product/PageHeader.vue';
import SearchField from '@/Components/Product/SearchField.vue';
import TemplateEditor from '@/Components/Communications/TemplateEditor.vue';
import AppLayout from '@/Layouts/AppLayout.vue';
import { deliveryLabel } from '@/Support/notificationWorkspace';
import '../../../css/communications.css';
const props=defineProps({business:Object,settings:Object,senderReadiness:Object,capabilities:Object,usage:Object,templates:Array,automations:Array,variableCatalog:Object,sampleValues:Object,defaults:Object,overview:Object,history:Object,historyFilters:Object,emailReadiness:Object});
const tab=ref((props.historyFilters?.client || props.historyFilters?.appointment)?'history':props.capabilities.manage?'automations':'history');
const editor=ref(null), detail=ref(null), retryDialog=ref(null), discard=ref(null);
const localTemplates=ref([...props.templates]), currentHistory=ref(props.history), selected=ref(null), historyBusy=ref(false), historyError=ref(''), retryBusy=ref(false), retryError=ref(''), retryReason=ref('');
const templateSearch=ref(''), group=ref('');
const filters=reactive({client:props.historyFilters?.client || '',appointment:props.historyFilters?.appointment || '',search:'',channel:'',status:'',type:'',from:'',to:''});
const form=useForm({default_locale:props.settings.default_locale, settings_revision:props.settings.settings_revision, reminder_offsets_minutes:[1440], quiet_hours_start:String(props.settings.quiet_hours_start || '21:00').slice(0,5),quiet_hours_end:String(props.settings.quiet_hours_end || '08:00').slice(0,5), marketing_enabled:false,mobile_channel:'sms',smart_fallback_enabled:false,sender_mode:props.settings.sender_mode,two_way_enabled:false});
const brandedForm=useForm({channels:['sms'],display_name:props.business.name});
const brandedProfile=computed(()=>(props.senderReadiness.profiles || []).find(p=>p.mode==='branded'&&p.channel==='sms'));
const brandedReady=computed(()=>brandedProfile.value?.status==='active');
const usagePercent=computed(()=>props.usage.included>0?Math.min(100,props.usage.used/props.usage.included*100):0);
const filteredAutomations=computed(()=>props.automations.filter(a=>(!group.value || a.group===group.value)&&(!templateSearch.value || (a.name+' '+a.trigger+' '+a.description).toLowerCase().includes(templateSearch.value.toLowerCase()))));
const groups=computed(()=>[...new Set(props.automations.map(a=>a.group))]);
const transport=computed(()=>({fake:{label:'Local simulation',detail:'SMS activity is simulated. No texts reach clients.',tone:'neutral'},twilio_test:{label:'Connection test',detail:'SMS requests are validated. No texts reach clients.',tone:'neutral'},live:props.senderReadiness.transport_ready?{label:'Live sending',detail:'Text delivery is enabled for eligible clients.',tone:'success'}:{label:'Sending needs attention',detail:'SMS delivery is paused or needs setup. Contact support.',tone:'warning'}}[props.senderReadiness.transport_mode]||{label:'SMS unavailable',detail:'Contact support to finish text delivery setup.',tone:'warning'}));
const templateStatus=(type,channel)=>localTemplates.value.find(t=>t.intent_type===type&&t.channel===channel&&t.locale===props.settings.default_locale)?.status==='draft'?'Draft ready':'Edit message';
function templateSaved(template){ const index=localTemplates.value.findIndex(t=>t.public_id===template.public_id); if(index>=0)localTemplates.value[index]=template;else localTemplates.value.unshift(template); }
function date(value,zone=props.business.time_zone){ if(!value)return '—'; return new Intl.DateTimeFormat(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit',timeZone:zone||'UTC'}).format(new Date(value)); }
function tone(message){if(message.simulated&&['sent','delivered'].includes(message.status))return 'neutral';return {failed:'danger',suppressed:'neutral',delivered:'success',sent:'info',retried:'warning',sending:'info',queued:'neutral'}[message.status]||'neutral';}
let requestSequence=0, aborter;
async function fetchHistory(page=1){
    const sequence=++requestSequence; aborter?.abort(); aborter=new AbortController(); historyBusy.value=true; historyError.value='';
    try{const response=await axios.get(route('business.communications.history',props.business.public_id),{params:{...filters,page},signal:aborter.signal});if(sequence===requestSequence)currentHistory.value=response.data.history;}
    catch(error){if(sequence===requestSequence&&!axios.isCancel(error))historyError.value=error.response?.data?.message||'History could not be loaded. Try again.';}
    finally{if(sequence===requestSequence)historyBusy.value=false;}
}
const filtersDirty=computed(()=>JSON.stringify(filters)!==appliedFilters.value);
const appliedFilters=ref(JSON.stringify(filters));
async function applyFilters(){await fetchHistory();if(!historyError.value)appliedFilters.value=JSON.stringify(filters);}
async function clearFilters(){Object.keys(filters).forEach(key=>filters[key]='');await applyFilters();}
function failedHistory(){tab.value='history';filters.status='failed';applyFilters();}
async function openMessage(message){selected.value=message;await detail.value.open();}
async function openRetry(){retryReason.value='';retryError.value='';await retryDialog.value.open();}
async function retry(){
    if(retryBusy.value)return;
    if(!retryReason.value.trim()){retryError.value='Describe the setup fix before retrying.';return;}
    retryBusy.value=true;
    try{const result=await axios.post(route('business.communications.messages.replay',[props.business.public_id,selected.value.id]),{reason:retryReason.value});selected.value=result.data.message;retryDialog.value.close();await fetchHistory(currentHistory.value.current_page);}
    catch(error){retryError.value=Object.values(error.response?.data?.errors || {}).flat().join(' ') || error.response?.data?.message || 'Retry result could not be confirmed. Refresh history before trying again.';}
    finally{retryBusy.value=false;}
}
const settingNotice=ref(''), settingsSubmitting=ref(false);
const save=()=>{settingsSubmitting.value=true;form.patch(route('business.communications.update',props.business.public_id),{preserveScroll:true,onSuccess:()=>{form.settings_revision=props.settings.settings_revision;form.defaults();settingNotice.value='Notification preferences saved.';},onFinish:()=>settingsSubmitting.value=false});};
const requestBranded=()=>brandedForm.post(route('business.communications.senders.branded',props.business.public_id),{preserveScroll:true});
const pendingTab=ref(null);
function switchTab(value){if(value===tab.value)return;if(form.isDirty){pendingTab.value=value;discard.value.open();}else tab.value=value;}
function discardSettings(){form.reset();tab.value=pendingTab.value;}
const stop=router.on('before',event=>{if(form.isDirty&&!settingsSubmitting.value){event.preventDefault();settingNotice.value='Save or discard your notification preferences before leaving.';}});
const unload=e=>{if(form.isDirty||form.processing){e.preventDefault();e.returnValue='';}};
if(typeof window!=='undefined')window.addEventListener('beforeunload',unload);
onBeforeUnmount(()=>{stop();aborter?.abort();if(typeof window!=='undefined')window.removeEventListener('beforeunload',unload);});
watch(()=>props.templates,values=>localTemplates.value=[...values]);
</script>
<template>
    <AppLayout title="Client notifications" :business-label="business.name">
        <div class="notify-workspace">
            <PageHeader title="Client notifications" description="Thoughtful messages. Clear timing. Every delivery accounted for."><template #actions><span :class="['notify-status',transport.tone]"><span/>{{ transport.label }}</span></template></PageHeader>
            <div class="notify-overview" aria-label="Communication overview">
                <div><span class="notify-stat-icon"><BellAlertIcon/></span><span><strong>{{ automations.filter(a=>!a.prepared).length }}</strong><small>Connected notification rules</small></span></div>
                <div><span class="notify-stat-icon"><CheckCircleIcon/></span><span><strong>{{ overview.counts.sent + overview.counts.delivered }}</strong><small>Sent or delivered · 7 days</small></span><span v-if="overview.counts.simulated" class="notify-muted">{{ overview.counts.simulated }} simulated separately</span></div>
                <button type="button" :class="{'notify-attention':overview.needs_attention}" @click="failedHistory"><span class="notify-stat-icon"><ExclamationTriangleIcon/></span><span><strong>{{ overview.needs_attention }}</strong><small>Failed · needs attention</small></span><ChevronRightIcon class="notify-small-icon"/></button>
            </div>
            <nav class="notify-tabs" aria-label="Client notifications sections"><button v-for="item in [{id:'automations',name:'Automations'},{id:'history',name:'Delivery history'},{id:'channels',name:'Channels & timing'}]" :key="item.id" type="button" :aria-current="tab===item.id?'page':undefined" @click="switchTab(item.id)">{{ item.name }}<span v-if="item.id==='history'&&overview.needs_attention" class="notify-tab-count">{{ overview.needs_attention }}</span></button></nav>
            <section v-if="tab==='automations'" aria-label="Notification automations">
                <div class="notify-section-intro"><div><h2>Keep clients in the loop</h2><p>Essential service updates, sent only to eligible clients.</p></div><span class="notify-muted"><ShieldCheckIcon class="notify-inline-icon"/> Consent checked before every send</span></div>
                <div class="notify-content-grid"><div class="notify-panel">
                    <div class="notify-toolbar"><SearchField v-model="templateSearch" label="Find an automation" placeholder="Search notifications…"/><label class="notify-label" for="automation-group">Category<select id="automation-group" v-model="group" class="cd-input"><option value="">All categories</option><option v-for="g in groups" :key="g">{{ g }}</option></select></label></div>
                    <div class="notify-list-heading"><span>Notification / trigger</span><span>Timing</span><span>Messages</span></div>
                    <article v-for="automation in filteredAutomations" :key="automation.type" class="notify-automation-row"><div class="notify-automation-info"><span class="notify-automation-icon"><ClockIcon v-if="automation.type==='appointment_reminder'"/><BellAlertIcon v-else/></span><div><h3>{{ automation.name }}</h3><p>{{ automation.trigger }}</p><span v-if="automation.prepared" class="notify-muted">Prepared template · no automatic trigger</span><span v-if="automation.type==='queue_update'||automation.type==='waitlist_opening'" class="notify-muted">{{ automation.type==='queue_update'?'Team-triggered':'Client-requested' }}</span></div></div><div class="notify-timing"><ArrowRightIcon aria-hidden="true"/><span>{{ automation.prepared?'Not scheduled':automation.timing }}</span></div><div class="notify-channel-actions"><button v-for="channel in ['email','sms']" :key="channel" type="button" :aria-label="`${capabilities.manage?'Edit':'Preview'} ${automation.name} ${channel==='email'?'email':'SMS'}`" @click="capabilities.manage ? editor.open(automation,channel) : undefined" :disabled="!capabilities.manage"><EnvelopeIcon v-if="channel==='email'"/><ChatBubbleLeftIcon v-else/>{{ channel==='email'?'Email':'SMS' }}<span v-if="templateStatus(automation.type,channel)==='Draft ready'" class="notify-draft-dot" title="Saved draft awaiting publish"/></button></div></article>
                    <div v-if="!filteredAutomations.length" class="notify-empty"><h3>No matching notifications</h3><p>Try another name or category.</p><button class="notify-text-action" type="button" @click="templateSearch='';group=''">Clear filters</button></div>
                    <div class="notify-panel-footnote">Email uses the available address and respects opt-outs. SMS requires an explicit selection, valid consent and an available sender. Waitlist offers use the requested channel.</div>
                </div><aside class="notify-side">
                    <section class="notify-panel notify-guide"><span class="notify-eyebrow">THE CLIENT JOURNEY</span><h2>Right message.<br>Right moment.</h2><ol><li><span>1</span><div><strong>Appointment confirmed</strong><p>Booking details arrive right away.</p></div></li><li><span>2</span><div><strong>A calm reminder</strong><p>24 hours before, around local quiet hours.</p></div></li><li><span>3</span><div><strong>Changes stay clear</strong><p>New details replace outdated reminders.</p></div></li></ol><p class="notify-muted">No extra reminder for last-minute bookings. Connected rules follow service events and client choices. This release has no per-rule pause controls.</p></section>
                    <section class="notify-panel notify-side-section"><h2>Coming up</h2><p class="notify-muted">Next queued messages · {{ business.time_zone }}</p><div v-if="!overview.upcoming.length" class="notify-quiet-empty"><ClockIcon/><p>No upcoming messages queued.</p><small>Eligible appointment reminders appear here.</small></div><button v-for="message in overview.upcoming" :key="message.id" type="button" class="notify-upcoming" @click="openMessage(message)"><strong>{{ message.name }}</strong><span>{{ message.client_name }} · {{ message.channel==='sms'?'SMS':'Email' }}</span><time>{{ date(message.scheduled_at) }}</time></button></section>
                    <p class="notify-side-note"><ShieldCheckIcon/>This center handles appointment and service communication. Promotional texts, campaigns and benefit-program messages are outside this release.</p>
                </aside></div>
            </section>
            <section v-if="tab==='history'" aria-label="Delivery history">
                <div class="notify-section-intro"><div><h2>Every message, a clear outcome</h2><p>Sent means accepted by the sending service. Delivered requires its confirmation.</p></div><AppButton variant="secondary" size="small" :disabled="historyBusy" @click="fetchHistory(currentHistory.current_page)"><ArrowPathIcon class="notify-small-icon"/>Refresh</AppButton></div>
                <div class="notify-panel">
                    <form class="notify-history-filters" @submit.prevent="applyFilters"><SearchField v-model="filters.search" label="Search history" :placeholder="capabilities.contact?'Client, exact email / phone, booking reference…':'Booking reference…'"/><label class="notify-label" for="history-channel">Channel<select id="history-channel" v-model="filters.channel" class="cd-input"><option value="">All channels</option><option value="email">Email</option><option value="sms">SMS</option></select></label><label class="notify-label" for="history-status">Status<select id="history-status" v-model="filters.status" class="cd-input"><option value="">All statuses</option><option v-for="status in ['queued','retried','sending','sent','delivered','failed','suppressed']" :key="status" :value="status">{{ deliveryLabel({status}) }}</option></select></label><AppButton type="submit" variant="secondary" :disabled="historyBusy">Apply</AppButton><button type="button" class="notify-text-action" @click="clearFilters">Reset</button><details class="notify-more-filters"><summary>More filters{{ filters.type||filters.from||filters.to?' · Active':'' }}</summary><div><label class="notify-label" for="history-type">Notification<select id="history-type" v-model="filters.type" class="cd-input"><option value="">All notifications</option><option v-for="a in automations" :key="a.type" :value="a.type">{{ a.name }}</option></select></label><label class="notify-label" for="history-from">From<input id="history-from" v-model="filters.from" type="date" class="cd-input"></label><label class="notify-label" for="history-to">To<input id="history-to" v-model="filters.to" type="date" class="cd-input"></label></div></details></form>
                    <div class="notify-history-caption"><span>{{ currentHistory.total }} {{ currentHistory.total===1?'message':'messages' }} · times in {{ business.time_zone }}</span><span v-if="historyBusy" role="status">Loading history…</span><span v-else-if="filtersDirty">Apply to update results</span><span v-else>{{ filters.appointment?'Appointment filter active · Reset for all messages':filters.client?'Client profile filter active · Reset for all clients':'25 per page' }}</span></div>
                    <div v-if="historyError" role="alert" class="notify-error">{{ historyError }} <button type="button" class="notify-text-action" @click="applyFilters">Try again</button></div>
                    <div class="notify-history-scroll" :aria-busy="historyBusy"><table v-if="currentHistory.data.length" class="notify-history-table"><thead><tr><th>Client & notification</th><th>Channel</th><th>Created</th><th>Outcome</th><th><span class="ds-sr-only">Details</span></th></tr></thead><tbody><tr v-for="message in currentHistory.data" :key="message.id"><td><strong>{{ message.client_name }}</strong><span>{{ message.name }}</span><small v-if="message.reference">{{ message.reference }}<template v-if="message.location"> · {{ message.location }}</template></small></td><td><span class="notify-channel-label"><EnvelopeIcon v-if="message.channel==='email'"/><ChatBubbleLeftIcon v-else/>{{ message.channel==='sms'?'SMS':'Email' }}</span></td><td><time :datetime="message.created_at">{{ date(message.created_at) }}</time></td><td><span :class="['notify-status',tone(message)]"><span/>{{ deliveryLabel(message) }}</span><small v-if="message.status==='failed'">Review delivery issue</small><small v-else-if="message.status==='suppressed'">Preference or policy applied</small><small v-else-if="message.simulated&&message.sent_at">No client delivery</small></td><td><button type="button" class="notify-detail-button" :aria-label="`View ${message.name} for ${message.client_name}`" @click="openMessage(message)">Details<ChevronRightIcon/></button></td></tr></tbody></table></div>
                    <div v-if="!currentHistory.data.length&&!historyBusy" class="notify-empty"><span class="notify-empty-icon"><ChatBubbleLeftIcon/></span><h3>{{ currentHistory.total===0&&Object.values(filters).some(Boolean)?'No messages match these filters':'Your communication history starts here' }}</h3><p>Eligible emails and texts appear after a booking or service event.<br>Simulated activity is labelled separately from real delivery.</p></div>
                    <div v-if="currentHistory.last_page>1" class="notify-pagination"><span>Page {{ currentHistory.current_page }} of {{ currentHistory.last_page }}</span><AppButton size="small" variant="secondary" :disabled="historyBusy||currentHistory.current_page===1||filtersDirty" @click="fetchHistory(currentHistory.current_page-1)">Previous</AppButton><AppButton size="small" variant="secondary" :disabled="historyBusy||currentHistory.current_page===currentHistory.last_page||filtersDirty" @click="fetchHistory(currentHistory.current_page+1)">Next</AppButton></div>
                </div>
            </section>
            <section v-if="tab==='channels'" aria-label="Channels and timing">
                <div class="notify-section-intro"><div><h2>A dependable connection</h2><p>Manage your client-facing sender and reminder preferences.</p></div></div>
                <div class="notify-settings-grid"><div class="notify-panel notify-settings-panel"><div class="notify-channel-health"><span class="notify-stat-icon"><EnvelopeIcon/></span><div><h3>Email</h3><p>Appointment updates and secure receipt links.</p></div><span :class="['notify-status',emailReadiness.configured?'info':'warning']"><span/>{{ emailReadiness.simulated?'Local simulation':emailReadiness.label }}</span></div><p class="notify-muted">{{ emailReadiness.simulated?'Email activity is simulated. No emails reach clients.':emailReadiness.configured?'Sending credentials are configured. Actual delivery appears in history; configuration alone does not certify delivery.':'Client email needs a sending connection. Ask your administrator or support to finish setup.' }}</p><div class="notify-channel-health"><span class="notify-stat-icon"><ChatBubbleLeftIcon/></span><div><h3>SMS</h3><p>{{ transport.detail }}</p></div><span :class="['notify-status',transport.tone]"><span/>{{ transport.label }}</span></div>
                    <p v-if="emailReadiness.configured&&!emailReadiness.simulated&&!emailReadiness.delivery_updates" class="notify-muted">Email sending is configured. Delivery confirmation still needs a verified delivery connection.</p><fieldset v-if="capabilities.manage" class="notify-senders"><legend>Client-facing text sender</legend><label><input v-model="form.sender_mode" type="radio" value="platform"><span><strong>ClipperDesk sender</strong><small>{{ business.name }} is named in every text.</small></span></label><label><input v-model="form.sender_mode" type="radio" value="branded" :disabled="!capabilities.branded_sender||!brandedReady"><span><strong>Your branded text line</strong><small>{{ !capabilities.branded_sender?'Not included in your plan':brandedReady?brandedProfile.display_name+' · '+(brandedProfile.sender||'Registered sender'):'Registration and approval required' }}</small></span></label></fieldset>
                    <div v-if="capabilities.manage&&capabilities.branded_sender&&!brandedProfile&&senderReadiness.branded_onboarding_available" class="notify-branded-setup"><h3>Prepare a branded line</h3><p class="notify-muted">Your existing sender stays in place while setup is reviewed.</p><label class="notify-label" for="branded-name">Business name<input id="branded-name" v-model="brandedForm.display_name" class="cd-input" :aria-invalid="!!brandedForm.errors.display_name"><FieldError :message="brandedForm.errors.display_name"/></label><AppButton size="small" variant="secondary" :disabled="brandedForm.processing" @click="requestBranded">Start branded setup</AppButton><FieldError :message="brandedForm.errors.channels"/></div><p v-else-if="brandedProfile" class="notify-muted">Branded line: {{ brandedProfile.status==='active'?'Ready': 'Awaiting approval' }}{{ senderReadiness.transport_mode==='fake'?' in local simulation. Production registration is still required.':'.' }}</p>
                    <div class="notify-usage"><div><strong>Included text messages</strong><span>{{ usage.included>0?usage.used.toLocaleString()+' / '+usage.included.toLocaleString():'No included allowance' }}</span></div><progress v-if="usage.included>0" :value="usagePercent" max="100" aria-label="Included text message allowance used"/><p class="notify-muted">Current subscription period · measured by messages, not estimated SMS segments.</p></div>
                    <p class="notify-side-note"><ShieldCheckIcon/>Client opt-outs and STOP replies take priority. Credentials are managed outside this workspace.</p>
                </div><form class="notify-panel notify-settings-panel" @submit.prevent="save"><h2>Reminder timing</h2><div class="notify-reminder-rule"><ClockIcon/><div><strong>One reminder · 24 hours before</strong><p>In the appointment’s location timezone. Quiet hours may move it to a suitable time before the appointment.</p></div></div><div class="notify-time-fields"><label class="notify-label" for="quiet-start">Quiet hours begin<input id="quiet-start" v-model="form.quiet_hours_start" type="time" class="cd-input" :disabled="!capabilities.manage" :aria-invalid="!!form.errors.quiet_hours_start" aria-describedby="quiet-start-error"><FieldError id="quiet-start-error" :message="form.errors.quiet_hours_start"/></label><label class="notify-label" for="quiet-end">Quiet hours end<input id="quiet-end" v-model="form.quiet_hours_end" type="time" class="cd-input" :disabled="!capabilities.manage" :aria-invalid="!!form.errors.quiet_hours_end" aria-describedby="quiet-end-error"><FieldError id="quiet-end-error" :message="form.errors.quiet_hours_end"/></label></div><p class="notify-muted">{{ form.quiet_hours_start===form.quiet_hours_end?'Matching times turn quiet hours off.':'Applies to scheduled reminders. Immediate confirmations, changes and requested alerts stay time-sensitive.' }} Existing queued reminders keep their scheduled time.</p><label class="notify-label" for="notification-locale">Default template locale<input id="notification-locale" v-model="form.default_locale" class="cd-input" placeholder="en-US" :disabled="!capabilities.manage" :aria-invalid="!!form.errors.default_locale" aria-describedby="locale-error locale-hint"><FieldError id="locale-error" :message="form.errors.default_locale"/></label><p id="locale-hint" class="notify-muted">Choose the template language to fall back to, such as en-US or en-GB. This does not translate your message text.</p><p v-for="(message,field) in form.errors" v-show="!['quiet_hours_start','quiet_hours_end','default_locale'].includes(field)" :key="field" class="notify-error" role="alert">{{ message }}</p><div v-if="capabilities.manage" class="notify-settings-save"><span role="status" class="notify-muted">{{ settingNotice || (form.isDirty?'Unsaved preferences':'Changes apply to new notifications') }}</span><AppButton type="submit" :disabled="form.processing||!form.isDirty">{{ form.processing?'Saving…':'Save preferences' }}</AppButton></div><p v-else class="notify-muted">Your role can view delivery history. A manager can edit these preferences.</p></form></div>
            </section>
        </div>
        <TemplateEditor v-if="capabilities.manage" ref="editor" :business="business" :templates="localTemplates" :defaults="defaults" :samples="sampleValues" :variables="variableCatalog" :locale="settings.default_locale" @saved="templateSaved"/>
        <AppDialog ref="detail" :title="selected?.name || 'Message details'" description="Delivery evidence for this notification." drawer><template v-if="selected"><div class="notify-detail-header"><span :class="['notify-status',tone(selected)]"><span/>{{ deliveryLabel(selected) }}</span><span>{{ selected.channel==='sms'?'SMS':'Email' }}</span></div><dl class="notify-detail-facts"><div><dt>Client</dt><dd><Link v-if="selected.client_id" :href="route('business.clients.show',[business.public_id,selected.client_id])">{{ selected.client_name }}</Link><template v-else>{{ selected.client_name }}</template></dd></div><div v-if="selected.recipient"><dt>Sent to</dt><dd>{{ selected.recipient }}</dd></div><div v-if="selected.reference"><dt>Appointment</dt><dd>{{ selected.reference }}</dd></div><div v-if="selected.location"><dt>Location</dt><dd>{{ selected.location }}</dd></div><div><dt>Timezone</dt><dd>{{ selected.time_zone }}</dd></div><div><dt>Send attempts</dt><dd>{{ selected.attempts }}</dd></div></dl><div v-if="selected.issue" class="notify-delivery-issue"><ExclamationTriangleIcon/><p>{{ selected.issue }}</p></div><ol class="notify-delivery-timeline"><li><strong>Created</strong><time>{{ date(selected.created_at,selected.time_zone) }}</time></li><li v-if="selected.scheduled_at"><strong>{{ selected.status==='retried'?'Retry scheduled':'Scheduled' }}</strong><time>{{ date(selected.scheduled_at,selected.time_zone) }}</time></li><li v-if="selected.sent_at"><strong>{{ selected.simulated?'Simulated acceptance':'Accepted by sending service' }}</strong><time>{{ date(selected.sent_at,selected.time_zone) }}</time></li><li v-if="selected.delivered_at"><strong>{{ selected.simulated?'Simulated outcome':'Delivery confirmed' }}</strong><time>{{ date(selected.delivered_at,selected.time_zone) }}</time></li><li v-if="selected.failed_at"><strong>Failed</strong><time>{{ date(selected.failed_at,selected.time_zone) }}</time></li></ol><p class="notify-muted">{{ selected.simulated?'Simulation is not proof that a client received this message.':selected.delivered_at?'Delivery was confirmed by the provider.':'Client delivery has not been confirmed.' }} Historical message bodies and secure links are not exposed here.</p><AppButton v-if="selected.can_retry" variant="secondary" @click="openRetry">Retry after fixing setup</AppButton></template><template #footer><AppButton variant="secondary" @click="detail.close()">Close</AppButton></template></AppDialog>
        <AppDialog ref="retryDialog" title="Retry this failed notification?" description="Confirm the sending issue has been fixed. This reuses the same message and checks consent again before sending." :close-on-confirm="false" :can-close="()=>!retryBusy" :confirm-disabled="retryBusy" :confirm-label="retryBusy?'Retrying…':'Queue retry'" @confirm="retry"><label class="notify-label" for="retry-reason">What was fixed?<textarea id="retry-reason" v-model="retryReason" class="cd-input" maxlength="1000" placeholder="Describe the connection or sender fix…" :aria-invalid="!!retryError" aria-describedby="retry-error"/><FieldError id="retry-error" :message="retryError"/></label></AppDialog>
        <AppDialog ref="discard" title="Discard unsaved preferences?" description="Your saved notification settings stay in place." confirm-label="Discard changes" @confirm="discardSettings"/>
    </AppLayout>
</template>
