<script setup>
import Breadcrumbs from '@/Components/Marketing/Breadcrumbs.vue';
import PublicContainer from '@/Components/Marketing/PublicContainer.vue';
import HomeLayout from '@/Layouts/HomeLayout.vue';
import { CheckIcon } from '@heroicons/vue/24/outline';
import { Head, Link } from '@inertiajs/vue3';
defineProps({ guide: Object });
</script>
<template><HomeLayout><Head :title="guide.title" /><article><header class="gh-public-section border-b border-[var(--border-subtle)]"><PublicContainer><Breadcrumbs :items="[{ label: 'Home', href: route('marketing.home') }, { label: 'Resources', href: route('marketing.resources') }, { label: guide.title }]" /><p class="gh-eyebrow mt-10">{{ guide.topic }}</p><h1 class="mt-5 max-w-4xl font-display text-[clamp(2.75rem,7vw,5rem)] font-semibold leading-[1] tracking-[-0.05em] text-[var(--text-strong)] text-balance">{{ guide.title }}</h1><p class="mt-7 max-w-3xl text-lg leading-8 text-[var(--text-muted)]">{{ guide.intro }}</p><p class="mt-6 text-sm font-semibold text-[var(--text-muted)]">Published {{ guide.published_at }} · Reviewed by {{ guide.reviewed_by }}</p></PublicContainer></header><section class="gh-public-section"><PublicContainer class="grid gap-12 lg:grid-cols-[1.15fr_0.85fr]"><div><ol class="space-y-9"><li v-for="(section, index) in guide.sections" :key="section.title"><p class="gh-eyebrow">Step {{ index + 1 }}</p><h2 class="mt-3 font-display text-3xl font-semibold text-[var(--text-strong)]">{{ section.title }}</h2><p class="mt-4 leading-8 text-[var(--text-muted)]">{{ section.body }}</p></li></ol></div><aside><div class="rounded-[var(--radius-xl)] border border-[var(--border-subtle)] bg-[var(--surface-subtle)] p-6"><h2 class="text-xl font-extrabold text-[var(--text-strong)]">Working checklist</h2><ul class="mt-5 space-y-3"><li v-for="item in guide.checklist" :key="item" class="flex gap-3 leading-7 text-[var(--text-muted)]"><CheckIcon class="mt-1 size-5 shrink-0 text-[var(--action-primary)]" aria-hidden="true" />{{ item }}</li></ul></div><div class="mt-5 rounded-[var(--radius-lg)] border-l-4 border-[var(--brand-rust)] bg-[var(--brand-cream)] p-6 leading-7 text-[var(--text-muted)]">{{ guide.limitation }}</div><Link :href="route('marketing.features.show', guide.feature)" class="gh-button gh-button-secondary mt-6">Explore the supporting feature</Link></aside></PublicContainer></section></article></HomeLayout></template>
