<script setup>
import Breadcrumbs from '@/Components/Marketing/Breadcrumbs.vue';
import MarketingCard from '@/Components/Marketing/MarketingCard.vue';
import PublicContainer from '@/Components/Marketing/PublicContainer.vue';
import HomeLayout from '@/Layouts/HomeLayout.vue';
import { Head, Link } from '@inertiajs/vue3';
defineProps({ guides: Array, articleCount: Number });
</script>
<template><HomeLayout><Head title="Good Hours resources for a clearer salon day" /><section class="gh-public-section border-b border-[var(--border-subtle)]"><PublicContainer><Breadcrumbs :items="[{ label: 'Home', href: route('marketing.home') }, { label: 'Resources' }]" /><p class="gh-eyebrow mt-10">Resources</p><h1 class="mt-5 max-w-4xl font-display text-[clamp(3rem,7vw,5.25rem)] font-semibold leading-[0.98] tracking-[-0.05em] text-[var(--text-strong)] text-balance">Practical guidance for the operating work behind a good day.</h1><p class="mt-7 max-w-3xl text-lg leading-8 text-[var(--text-muted)]">Start with a maintained guide, then browse only articles that have a named author, review evidence and a real publication date.</p></PublicContainer></section><section class="gh-public-section"><PublicContainer><div class="grid gap-5 md:grid-cols-2"><MarketingCard v-for="guide in guides" :key="guide.slug"><p class="gh-eyebrow">{{ guide.topic }}</p><h2 class="mt-4 text-2xl font-extrabold text-[var(--text-strong)]">{{ guide.title }}</h2><p class="mt-4 leading-7 text-[var(--text-muted)]">{{ guide.description }}</p><Link :href="route('marketing.guides.show', guide.slug)" class="mt-6 inline-flex min-h-11 items-center font-extrabold text-[var(--brand-pine)] underline-offset-4 hover:underline">Read the guide</Link></MarketingCard></div><div class="mt-12 flex flex-col gap-5 rounded-[var(--radius-xl)] bg-[var(--brand-pine)] p-7 text-white sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-display text-3xl">Good Hours editorial</h2><p class="mt-2 text-white/78">{{ articleCount }} reviewed {{ articleCount === 1 ? 'article is' : 'articles are' }} currently published.</p></div><Link :href="route('blog.index')" class="gh-button bg-white text-[var(--brand-pine)]">Browse the blog</Link></div></PublicContainer></section></HomeLayout></template>
