<script setup>
import { computed } from 'vue';
import { useForm, usePage } from '@inertiajs/vue3';
import { LockClosedIcon } from '@heroicons/vue/24/outline';
import AppButton from '@/Components/Product/AppButton.vue';
import FormField from '@/Components/Product/FormField.vue';
import StatePanel from '@/Components/Product/StatePanel.vue';
import SurfaceCard from '@/Components/Product/SurfaceCard.vue';
import PublicBookingLayout from '@/Layouts/PublicBookingLayout.vue';

const props = defineProps({ appointment: Object, actions: Object, purpose: String, actionToken: String, activeWaitlists: { type: Array, default: () => [] } });
const page = usePage();
const localTime = computed(() => props.appointment ? new Intl.DateTimeFormat(undefined, { dateStyle: 'full', timeStyle: 'short', timeZone: props.appointment.time_zone }).format(new Date(props.appointment.starts_at)) : '');
const money = computed(() => props.appointment ? new Intl.NumberFormat(undefined, { style: 'currency', currency: props.appointment.currency_code }).format(props.appointment.price_minor / 100) : '');
const actionRoute = computed(() => props.actionToken ? route('public.appointment.mutate', [props.actionToken, props.purpose]) : '');
const cancellationForm = useForm({ confirmed: false, idempotency_key: '' });
const rescheduleForm = useForm({ starts_at: '', confirmed: false, idempotency_key: '' });
const contactForm = useForm({ name: props.appointment?.client_name || '', mobile: props.appointment?.client_mobile || '', email: props.appointment?.client_email || '', idempotency_key: '' });
const waitlistForm = useForm({ operation: 'join', acceptable_from: '', acceptable_until: '', time_from: '09:00', time_until: '18:00', notification_method: 'email', notes: '', idempotency_key: '' });
const rebookForm = useForm({ idempotency_key: '' });
const submit = form => { form.idempotency_key ||= `self-service-${props.purpose}-${crypto.randomUUID()}`; form.post(actionRoute.value, { preserveScroll: true }); };
const leaveWaitlist = entry => useForm({ operation: 'leave', waitlist_request: entry.public_id, version: entry.version }).post(actionRoute.value, { preserveScroll: true });
</script>

<template>
    <PublicBookingLayout title="Manage an appointment" mode="self-service">
        <template v-if="!appointment"><p class="text-xs font-semibold uppercase tracking-[0.12em] text-[var(--action-primary)]">Secure self-service</p><h1 class="gh-display mt-2 text-4xl text-[var(--text-strong)]">Open your private appointment link</h1><SurfaceCard class="mt-8"><StatePanel tone="info" title="Use the link in your confirmation" description="For privacy, booking references cannot be searched here. Ask the business to send a fresh secure link if yours expired."><template #actions><AppButton :href="route('booking.welcome')" variant="secondary">Back to booking</AppButton></template></StatePanel></SurfaceCard></template>
        <template v-else>
            <p class="text-xs font-semibold uppercase tracking-[0.12em] text-[var(--action-primary)]"><LockClosedIcon class="mr-1 inline size-4" aria-hidden="true" />Secure self-service</p><h1 class="gh-display mt-2 text-4xl text-[var(--text-strong)]">{{ appointment.business }}</h1><p class="mt-2 text-sm text-[var(--text-muted)]">Reference {{ appointment.reference }} · Keep this page private on a shared device.</p>
            <p v-if="page.props.flash?.status" class="mt-5 rounded-xl bg-[var(--status-success-soft)] p-4 text-sm font-semibold text-[var(--status-success)]" role="status">{{ page.props.flash.status }}</p><p v-if="page.props.errors?.appointment" class="mt-5 rounded-xl bg-[var(--status-danger-soft)] p-4 text-sm text-[var(--status-danger)]" role="alert">{{ page.props.errors.appointment }}</p>
            <SurfaceCard class="mt-6" title="Appointment details" :description="appointment.status.replaceAll('_', ' ')"><dl class="grid gap-4 text-sm sm:grid-cols-2"><div><dt class="font-semibold text-[var(--text-muted)]">When</dt><dd class="mt-1 text-[var(--text-strong)]">{{ localTime }}<br>{{ appointment.time_zone }}</dd></div><div><dt class="font-semibold text-[var(--text-muted)]">Where</dt><dd class="mt-1 text-[var(--text-strong)]">{{ appointment.location }}</dd></div><div><dt class="font-semibold text-[var(--text-muted)]">Services</dt><dd class="mt-1 text-[var(--text-strong)]">{{ appointment.services.join(', ') }}</dd></div><div><dt class="font-semibold text-[var(--text-muted)]">Price / deposit</dt><dd class="mt-1 text-[var(--text-strong)]">{{ money }} · {{ appointment.deposit_status.replaceAll('_', ' ') }}</dd></div></dl><p class="mt-5 rounded-lg bg-[var(--surface-subtle)] p-3 text-sm"><strong>Cancellation policy:</strong> {{ appointment.cancellation_policy }}</p></SurfaceCard>

            <SurfaceCard v-if="!purpose" class="mt-5" title="What would you like to do?" description="Choose one action. For your privacy, each secure link works only for that task and expires automatically."><div class="grid gap-3 sm:grid-cols-2"><AppButton v-if="actions.reschedule" :href="actions.reschedule" variant="secondary">Reschedule</AppButton><AppButton v-if="actions.cancel" :href="actions.cancel" variant="danger">Cancel</AppButton><AppButton v-if="actions.rebook" :href="actions.rebook" variant="secondary">Book again</AppButton><AppButton v-if="actions.contact" :href="actions.contact" variant="secondary">Update contact</AppButton><AppButton v-if="actions.waitlist" :href="actions.waitlist" variant="secondary">Join waitlist</AppButton><AppButton v-if="actions.payment_status" :href="actions.payment_status" variant="secondary">Payment status</AppButton></div></SurfaceCard>

            <SurfaceCard v-else-if="purpose === 'cancel'" class="mt-5" title="Cancel this appointment?" description="This action cannot be undone. An opening may be offered to the waitlist."><label class="flex min-h-11 items-center gap-3"><input v-model="cancellationForm.confirmed" type="checkbox" />I understand this cancels the appointment</label><AppButton class="mt-4 w-full" variant="danger" :disabled="!cancellationForm.confirmed" @click="submit(cancellationForm)">Cancel appointment</AppButton></SurfaceCard>
            <SurfaceCard v-else-if="purpose === 'reschedule'" class="mt-5" title="Choose a new time" description="The new time, staff, resource capacity, and current policy are checked again before anything changes."><FormField id="reschedule-time" label="New local date and time" required><input id="reschedule-time" v-model="rescheduleForm.starts_at" type="datetime-local" class="min-h-11 w-full rounded-lg border px-3" /></FormField><label class="mt-3 flex min-h-11 items-center gap-3"><input v-model="rescheduleForm.confirmed" type="checkbox" />Confirm replacement after capacity check</label><AppButton class="mt-4 w-full" :disabled="!rescheduleForm.starts_at || !rescheduleForm.confirmed" @click="submit(rescheduleForm)">Reschedule</AppButton></SurfaceCard>
            <SurfaceCard v-else-if="purpose === 'contact'" class="mt-5" title="Update contact details" description="Your appointment stays linked while the business receives the corrected contact details."><div class="grid gap-4"><FormField id="contact-name" label="Name" required><input id="contact-name" v-model="contactForm.name" autocomplete="name" class="gh-input" /></FormField><FormField id="contact-mobile" label="Mobile" required><input id="contact-mobile" v-model="contactForm.mobile" autocomplete="tel" inputmode="tel" class="gh-input" /></FormField><FormField id="contact-email" label="Email" required><input id="contact-email" v-model="contactForm.email" type="email" autocomplete="email" class="gh-input" /></FormField></div><AppButton class="mt-4 w-full" @click="submit(contactForm)">Save contact details</AppButton></SurfaceCard>
            <SurfaceCard v-else-if="purpose === 'waitlist'" class="mt-5" title="Manage waitlist" description="Choose the dates and times that could work. Good Hours keeps one active request for the same opening preferences."><div v-if="activeWaitlists.length" class="mb-5 space-y-3"><p class="text-sm font-semibold text-[var(--text-strong)]">Your active requests</p><div v-for="entry in activeWaitlists" :key="entry.public_id" class="flex flex-col gap-3 rounded-lg bg-[var(--surface-subtle)] p-3 text-sm sm:flex-row sm:items-center sm:justify-between"><span>{{ entry.service }} · {{ entry.from }} to {{ entry.until }} · {{ entry.time_from }}–{{ entry.time_until }}</span><AppButton variant="secondary" @click="leaveWaitlist(entry)">Leave</AppButton></div></div><div class="grid gap-4 sm:grid-cols-2"><input v-model="waitlistForm.acceptable_from" type="date" aria-label="Acceptable from" class="gh-input" /><input v-model="waitlistForm.acceptable_until" type="date" aria-label="Acceptable until" class="gh-input" /><input v-model="waitlistForm.time_from" type="time" aria-label="Time from" class="gh-input" /><input v-model="waitlistForm.time_until" type="time" aria-label="Time until" class="gh-input" /><select v-model="waitlistForm.notification_method" aria-label="Notification method" class="gh-input"><option value="email">Email</option><option value="whatsapp">WhatsApp</option></select></div><AppButton class="mt-4 w-full" @click="submit(waitlistForm)">Join waitlist</AppButton></SurfaceCard>
            <SurfaceCard v-else-if="purpose === 'payment_status'" class="mt-5" title="Deposit and payment status"><StatePanel tone="info" :title="appointment.deposit_status === 'not_required' ? 'No deposit required' : 'Deposit collection is not available online yet'" description="The business will contact you if a deposit is needed. Good Hours does not collect card details on this page." /></SurfaceCard>
            <SurfaceCard v-else class="mt-5" title="Book this again" description="A new booking always checks current services, prices, policies, staff, and capacity."><AppButton class="w-full" @click="submit(rebookForm)">Start a new booking</AppButton></SurfaceCard>
        </template>
    </PublicBookingLayout>
</template>
