<script setup>
import { computed, ref, watch, nextTick } from 'vue';
import { useForm, router } from '@inertiajs/vue3';
import { CalendarDaysIcon, PlusIcon, XMarkIcon, ArrowTopRightOnSquareIcon, ClockIcon } from '@heroicons/vue/24/outline';
import AppDialog from '@/Components/Product/AppDialog.vue';
import AppSelect from '@/Components/Product/AppSelect.vue';
import AppButton from '@/Components/Product/AppButton.vue';
import PhoneInput from '@/Components/Product/PhoneInput.vue';
import SearchField from '@/Components/Product/SearchField.vue';
import AccessPanel from './AccessPanel.vue';
import { dayNames, isTimeOff, ruleLabel, staffDay, shiftRules, durationLabel, initialName, localDate, tabKey } from '@/Support/teamWorkspace';
import { parseMoney, moneyInput } from '@/Support/checkoutWorkspace';
const props=defineProps({business:Object,staff:Array,locations:Array,services:Array,schedule:Object,upcomingSchedule:Object,date:String,location:Object,now:Number,can:Object,roles:Array,modules:Array,grantable:Array,canManageOwners:Boolean,updatedAt:String,invitations:Array});
const emit=defineEmits(['close','saved','refresh']);
const dialog=ref(null), selectedId=ref(null), tab=ref('overview'), profileEditing=ref(false), accessDirty=ref(false), accessBusy=ref(false), discardWanted=ref(null);
const invitation=computed(()=>props.invitations?.find(i=>i.staff_id===selectedId.value));
const person=computed(()=>props.staff.find(p=>p.public_id===selectedId.value));
const today=computed(()=>localDate(props.now,props.location?.time_zone || props.business.time_zone));
const day=computed(()=>props.schedule.days.find(d=>d.date===props.date));
const state=computed(()=>person.value?staffDay(person.value,day.value,props.now,props.location?.time_zone || props.business.time_zone,today.value):null);
const stale=computed(()=>props.now-Date.parse(props.updatedAt)>120000);
watch(()=>props.updatedAt,()=>{if(!dirty.value && !busy.value)reset();});
const zone=computed(()=>props.location?.time_zone || props.business.time_zone);
const time=(value,timeZone=zone.value)=>new Intl.DateTimeFormat(undefined,{timeZone,hour:'numeric',minute:'2-digit'}).format(new Date(value));
const clock=value=>value?new Intl.DateTimeFormat(undefined,{timeZone:'UTC',hour:'numeric',minute:'2-digit'}).format(new Date(`2000-01-01T${value.slice(0,5)}:00Z`)):'Off';
const dayLabel=date=>new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric',timeZone:'UTC'}).format(new Date(`${date}T12:00Z`));
const fraction=currency=>10**new Intl.NumberFormat(undefined,{style:'currency',currency:currency || props.business.currency_code}).resolvedOptions().maximumFractionDigits;
const money=(value,currency)=>new Intl.NumberFormat(undefined,{style:'currency',currency:currency || props.business.currency_code}).format(value/fraction(currency));
const calendarUrl=(date=props.date,appointment=null)=>route('business.calendar',{business:props.business.public_id,location:props.location?.public_id,date,staff:[selectedId.value],...(appointment?{appointment}:{}),view:'staff'});
const profile=useForm({display_name:'',title:'',email:'',mobile:'',biography:'',status:'active',online_visible:true,location_ids:[],profile_revision:'',reason:''});
const scheduleForm=useForm({rules:[],revision:'',impact_preview_id:'',impact_reason:''});
const serviceForm=useForm({assignments:[],services_revision:'',reason:''});
const reviewing=ref(false), review=ref(null), reviewError=ref(''), retained=ref(false), hoursAcknowledged=ref(false), saving=ref(false);
const priceDrafts=ref({}), priceErrors=ref({});
const showException=ref(false), copyDay=ref(1), serviceSearch=ref('');
const exception=ref({kind:'leave',recurrence:'dated',location_id:null,day_of_week:1,starts_on:'',ends_on:'',full_day:true,starts_at:'13:00',ends_at:'13:30',reason:''});
let reviewAbort, reviewGeneration=0;
const scheduleDirty=computed(()=>scheduleForm.isDirty && JSON.stringify(scheduleForm.rules)!==scheduleOriginal.value);
const scheduleOriginal=ref('[]');
const dirty=computed(()=>Object.keys(priceErrors.value).length>0 || showException.value || profile.isDirty || scheduleDirty.value || serviceForm.isDirty || accessDirty.value);
const busy=computed(()=>accessBusy.value || profile.processing || scheduleForm.processing || serviceForm.processing || reviewing.value || saving.value);
const reset=()=>{
 if(!person.value)return;
 const p=person.value;
 profile.defaults({display_name:p.display_name,title:p.title || '',email:p.email || '',mobile:p.mobile || '',biography:p.biography || '',status:p.status,online_visible:p.online_visible,location_ids:p.locations.map(l=>l.public_id),profile_revision:p.profile_revision,reason:''});profile.reset();profile.clearErrors();
 scheduleForm.defaults({rules:JSON.parse(JSON.stringify(p.availability.filter(r=>!r.ends_on || r.ends_on>=localDate(props.now,props.locations.find(l=>l.id===r.location_id)?.time_zone || props.business.time_zone)))),revision:p.revision,impact_preview_id:'',impact_reason:''});scheduleForm.reset();scheduleForm.clearErrors();scheduleOriginal.value=JSON.stringify(scheduleForm.rules);
 serviceForm.defaults({assignments:p.services.map(s=>({service:s.public_id,is_qualified:s.is_qualified,online_visible:s.online_visible,duration_minutes:s.duration_override,price_minor:s.price_override})),services_revision:p.services_revision,reason:''});serviceForm.reset();serviceForm.clearErrors();
 priceDrafts.value={};priceErrors.value={};review.value=null;reviewError.value='';retained.value=false;hoursAcknowledged.value=false;showException.value=false;accessDirty.value=false;accessBusy.value=false;discardWanted.value=null;profileEditing.value=false;serviceSearch.value='';
};
const close=()=>{if(busy.value)return false;if(dirty.value){discardWanted.value={kind:'close'};nextTick(()=>document.querySelector('.tm-confirm-unsaved')?.scrollIntoView({block:'center'}));return false;}emit('close');return true;};
const requestTab=target=>{if(busy.value)return;if(dirty.value){discardWanted.value={kind:'tab',tab:target};nextTick(()=>document.querySelector('.tm-confirm-unsaved')?.scrollIntoView({block:'center'}));return;}tab.value=target;nextTick(()=>document.querySelector('dialog[open] .cd-dialog-body')?.scrollTo({top:0}));};
const discard=()=>{const action=discardWanted.value;reset();if(action?.kind==='close'){dialog.value?.close();emit('close');}else if(action?.kind==='tab')tab.value=action.tab;else if(action?.kind==='navigate')router.visit(action.url);};
const navigate=url=>{if(busy.value)return;if(dirty.value){discardWanted.value={kind:'navigate',url};nextTick(()=>document.querySelector('.tm-confirm-unsaved')?.scrollIntoView({block:'center'}));return;}router.visit(url);};
const open=async(id,target='overview')=>{selectedId.value=id;tab.value=target;await nextTick();reset();await dialog.value?.open();};
defineExpose({open});
watch(()=>JSON.stringify(scheduleForm.rules),()=>{reviewGeneration++;reviewAbort?.abort();reviewing.value=false;review.value=null;scheduleForm.impact_preview_id='';retained.value=false;hoursAcknowledged.value=false;});
const allRules=day=>scheduleForm.rules.filter(r=>r.kind==='working' && r.day_of_week===day);
const newRule=(day,locationId=props.location?.id)=>({kind:'working',location_id:locationId || props.locations[0]?.id || null,day_of_week:day,starts_on:null,ends_on:null,starts_at:'09:00',ends_at:'18:00',sequence:1,reason:null});
const toggleDay=(day,enabled)=>{if(enabled)scheduleForm.rules.push(newRule(day));else scheduleForm.rules=scheduleForm.rules.filter(r=>!(r.kind==='working' && r.day_of_week===day));};
const removeRule=rule=>scheduleForm.rules=scheduleForm.rules.filter(r=>r!==rule);
const copyWeekdays=()=>{
 const source=allRules(Number(copyDay.value)).map(r=>({...r}));if(!source.length)return;
 scheduleForm.rules=scheduleForm.rules.filter(r=>!(r.kind==='working' && r.day_of_week<=5));
 for(let day=1;day<=5;day++)scheduleForm.rules.push(...source.map((r,i)=>({...r,day_of_week:day,sequence:i+1})));
};
const useBranchHours=()=>{
 if(!props.location)return;
 scheduleForm.rules=scheduleForm.rules.filter(r=>r.kind!=='working' || (r.location_id && r.location_id!==props.location.id));
 for(const h of props.location.hours)scheduleForm.rules.push({...newRule(h.day_of_week),starts_at:h.opens_at.slice(0,5),ends_at:h.closes_at.slice(0,5),sequence:h.sequence || 1});
};
const openException=kind=>{showException.value=true;exception.value={kind,recurrence:'dated',location_id:props.location?.id || props.locations[0]?.id || null,day_of_week:new Date(`${props.date}T12:00Z`).getUTCDay() || 7,starts_on:props.date,ends_on:props.date,full_day:kind==='leave',starts_at:'13:00',ends_at:'13:30',reason:''};reviewError.value='';};
const addException=()=>{
 const e=exception.value;const dated=e.recurrence==='dated' || !['break','personal_block'].includes(e.kind);const timed=!isTimeOff(e) || !e.full_day;
 if(dated && e.ends_on<localDate(props.now,props.locations.find(l=>l.id===Number(e.location_id))?.time_zone || props.business.time_zone)){reviewError.value='Past exceptions are preserved as history. Choose a current or future end date.';return;}
 if((dated && (!e.starts_on || !e.ends_on || e.ends_on<e.starts_on)) || (timed && (!e.starts_at || !e.ends_at || e.ends_at<=e.starts_at))){reviewError.value='Choose valid dates and an end time after the start.';return;}
 scheduleForm.rules.push({kind:e.kind,location_id:e.location_id?Number(e.location_id):null,day_of_week:dated?null:Number(e.day_of_week),starts_on:dated?e.starts_on:null,ends_on:dated?e.ends_on:null,starts_at:timed?e.starts_at:null,ends_at:timed?e.ends_at:null,sequence:1,reason:e.reason || null});showException.value=false;reviewError.value='';
};
const exceptions=computed(()=>scheduleForm.rules.filter(r=>r.kind!=='working' && (!r.ends_on || r.ends_on>=today.value)).sort((a,b)=>(a.starts_on || '').localeCompare(b.starts_on || '')));
const preview=async()=>{
 reviewing.value=true;reviewError.value='';scheduleForm.clearErrors();reviewAbort?.abort();reviewAbort=new AbortController();const generation=++reviewGeneration;
 try{
  const response=await fetch(route('business.team.schedule.preview',[props.business.public_id,person.value.public_id]),{method:'POST',signal:reviewAbort.signal,headers:{Accept:'application/json','Content-Type':'application/json','X-XSRF-TOKEN':decodeURIComponent(document.cookie.match(/(?:^|; )XSRF-TOKEN=([^;]+)/)?.[1] || '')},body:JSON.stringify({rules:scheduleForm.rules,revision:scheduleForm.revision})});
  const data=await response.json();if(!response.ok)throw new Error(Object.values(data.errors || {}).flat()[0] || 'Could not review this schedule. Try again.');
  if(generation===reviewGeneration){review.value=data;scheduleForm.impact_preview_id=data.public_id;await nextTick();document.getElementById('staff-impact-heading')?.focus();}
 }catch(error){if(error.name!=='AbortError' && generation===reviewGeneration)reviewError.value=error.message || 'Connection lost. Your edits are still here.';}
 finally{if(generation===reviewGeneration)reviewing.value=false;}
};
const saved=()=>{reset();emit('saved');};
const saveSchedule=()=>scheduleForm.put(route('business.team.schedule.update',[props.business.public_id,person.value.public_id]),{preserveScroll:true,onSuccess:saved,onError:errors=>{if(errors.preview){review.value=null;scheduleForm.impact_preview_id='';}},onNetworkError:()=>{reviewError.value='Connection lost. Retry this exact reviewed schedule to check whether it saved.';return false;}});
const saveProfile=()=>profile.patch(route('business.team.profile.update',[props.business.public_id,person.value.public_id]),{preserveScroll:true,onSuccess:saved});
const serviceGroups=computed(()=>{
 const catalogue=[...props.services,...(person.value?.services || []).filter(s=>!props.services.some(c=>c.public_id===s.public_id))];
 return [...new Set(catalogue.map(s=>s.category))].map(category=>({category,services:catalogue.filter(s=>s.category===category && s.name.toLocaleLowerCase().includes(serviceSearch.value.toLocaleLowerCase()))})).filter(g=>g.services.length);
});
const assignment=s=>serviceForm.assignments.find(a=>a.service===s.public_id);
const toggleService=(s,checked)=>{if(checked){const a=assignment(s);if(a)a.is_qualified=true;else serviceForm.assignments.push({service:s.public_id,is_qualified:true,online_visible:true,duration_minutes:null,price_minor:null});}else{const a=assignment(s);if(a)a.is_qualified=false;}};
const selectCategory=(services,selected)=>services.forEach(s=>toggleService(s,selected));
const setPrice=(s,text)=>{priceDrafts.value[s.public_id]=text;const minor=text===''?null:parseMoney(text,s.currency_code);if(text!=='' && minor===null)priceErrors.value[s.public_id]='Use a valid amount in '+s.currency_code;else{delete priceErrors.value[s.public_id];assignment(s).price_minor=minor;}};
const saveServices=()=>{if(Object.keys(priceErrors.value).length)return;serviceForm.put(route('business.team.services.update',[props.business.public_id,person.value.public_id]),{preserveScroll:true,onSuccess:saved});};
const appointments=computed(()=>person.value?.appointments.filter(a=>localDate(Date.parse(a.starts_at),zone.value)===props.date) || []);
const upcomingShifts=computed(()=>(props.upcomingSchedule?.days || props.schedule.days).filter(d=>d.date>=props.date).slice(0,4).map(d=>{const context=d.staff.find(s=>s.id===person.value?.public_id);return {date:d.date,rules:person.value?shiftRules(person.value,d.date,props.location?.id):[],off:!context?.windows.length?(context?.unavailable.some(isTimeOff)?'Time off':!d.windows.length?'Branch closed':person.value?.status!=='active'?'Inactive':null):null};}));
const bookingGaps=computed(()=>state.value?.state==='overrun'?[]:(state.value?.gaps || []).filter(g=>props.date!==today.value || Date.parse(g.endsAt)>props.now).map(g=>({...g,startsAt:props.date===today.value?new Date(Math.max(Date.parse(g.startsAt),props.now)).toISOString():g.startsAt})).slice(0,5));
const profileTabs=computed(()=>['overview','schedule','services',...(props.can.manage?['access']:[])]);
const currentShift=computed(()=>person.value?shiftRules(person.value,props.date,props.location?.id):[]);
const statement=ref(null),statementBusy=ref(false),statementError=ref('');
const loadStatement=async()=>{const requested=selectedId.value;statementBusy.value=true;statementError.value='';try{const response=await fetch(route('business.staff.statement',{business:props.business.public_id,staff:person.value.public_id,start_date:props.date.slice(0,7)+'-01',end_date:props.date}),{headers:{Accept:'application/json'}});if(!response.ok)throw new Error();const data=await response.json();if(requested===selectedId.value)statement.value=data.statement;}catch{statementError.value='Commission statement could not be loaded.';}finally{statementBusy.value=false;}};
watch(selectedId,()=>{statement.value=null;statementError.value='';});
</script>
<template>
 <AppDialog ref="dialog" class="tm-drawer" drawer title="Staff profile" description="Working profile, schedule and capabilities." :can-close="close">
  <template v-if="person">
   <div class="tm-profile-heading"><span class="tm-avatar" aria-hidden="true">{{ initialName(person.display_name) }}</span><div class="min-w-0"><strong>{{ person.display_name }}</strong><p>{{ person.title || 'Team member' }} · {{ person.locations.map(l=>l.name).join(' · ') || 'No branch assigned' }}</p></div></div>
   <div class="tm-profile-actions"><AppButton v-if="stale" variant="secondary" size="small" :disabled="dirty || busy" @click="emit('refresh')">Refresh availability</AppButton><AppButton v-if="can.calendar" @click="navigate(calendarUrl())" variant="secondary" size="small"><CalendarDaysIcon class="size-4" />View calendar</AppButton><AppButton v-if="person.can_edit" variant="quiet" size="small" @click="requestTab('schedule')">Edit schedule</AppButton><AppButton v-if="person.can_edit" variant="quiet" size="small" @click="requestTab('schedule'); if(tab==='schedule')openException('leave')">Add time off</AppButton></div>
   <div class="tm-tabs tm-profile-tabs" role="tablist" aria-label="Staff profile sections"><button v-for="section in profileTabs" :id="`profile-tab-${section}`" :key="section" type="button" role="tab" :aria-selected="tab===section" :tabindex="tab===section?0:-1" @keydown="tabKey($event,profileTabs,tab,requestTab,'profile-tab-')" :aria-controls="`profile-panel-${section}`" @click="requestTab(section)">{{ {overview:'Overview',schedule:'Schedule',services:'Services',access:'Access'}[section] }}</button></div>
   <div class="tm-profile-content" :id="`profile-panel-${tab}`" role="tabpanel" :aria-labelledby="`profile-tab-${tab}`">
    <div v-if="discardWanted" class="tm-confirm-unsaved" role="alert"><span>You have unsaved changes.</span><button type="button" @click="discardWanted=null">Keep editing</button><button type="button" @click="discard">Discard changes</button></div>
    <template v-if="tab==='overview'">
     <div class="tm-summary-grid"><div><strong class="tm-small-value"><span :class="['tm-status',`tm-state-${state.state}`]"><i class="tm-dot" />{{ stale && date===today?'Needs refresh':state.label }}</span></strong><span>{{ state.until?'Until '+time(state.until):props.date===today?'Right now':dayLabel(date) }}</span></div><div><strong>{{ durationLabel(state.bookedMinutes) }}</strong><span>Reserved / {{ durationLabel(state.scheduledMinutes) }} bookable</span></div><div><strong>{{ state.scheduledMinutes ? state.utilization+'%' : '—' }}</strong><span>Staff time reserved</span></div></div>
     <h3>Working profile <button v-if="person.can_edit && !profileEditing" type="button" @click="profileEditing=true">Edit profile</button></h3>
     <form v-if="profileEditing" @submit.prevent="saveProfile" class="tm-field-grid">
      <label>Name<input v-model="profile.display_name" :aria-invalid="!!profile.errors.display_name" required maxlength="255" class="cd-input" /></label><label>Professional title<input v-model="profile.title" :aria-invalid="!!profile.errors.title" maxlength="120" class="cd-input" /></label>
      <label>Email<input v-model="profile.email" :aria-invalid="!!profile.errors.email" type="email" :disabled="!!person.membership" class="cd-input" /></label><label for="staff-profile-mobile">Mobile<PhoneInput id="staff-profile-mobile" v-model="profile.mobile" :country="business.country_code" class="mt-1.5" /></label>
      <label>Employment status<AppSelect v-model="profile.status" :aria-invalid="!!profile.errors.status" class="cd-input"><option value="active">Active / bookable</option><option value="inactive">Inactive / not bookable</option></AppSelect></label><label class="tm-check"><input v-model="profile.online_visible" type="checkbox" />Clients can choose them online</label>
      <fieldset class="full"><legend class="tm-block-label">Branches they work at</legend><label v-for="l in locations" :key="l.public_id" class="tm-check"><input v-model="profile.location_ids" type="checkbox" :value="l.public_id" />{{ l.name }}</label></fieldset>
      <label class="full">Biography <span class="tm-meta">optional</span><textarea v-model="profile.biography" :aria-invalid="!!profile.errors.biography" class="cd-input" rows="2" maxlength="2000" /></label><label class="full">Reason for status or branch change<textarea v-model="profile.reason" :aria-invalid="!!profile.errors.reason" rows="2" class="cd-input" placeholder="Required when existing appointments are affected" /></label>
      <p v-if="profile.status==='inactive'" class="tm-meta full">This removes future bookability. Existing visits stay visible and login access is managed separately.</p><div v-if="Object.keys(profile.errors).length" class="tm-error full" role="alert"><p v-for="(e,k) in profile.errors" :key="k">{{ e }}</p></div><AppButton type="submit" :disabled="profile.processing" class="full">Save profile</AppButton>
     </form>
     <div v-else class="tm-field-grid"><div v-if="person.contact_visible"><p class="tm-meta">Contact</p><p class="text-xs mt-1 break-all">{{ person.email || 'No email recorded' }}</p><p v-if="person.mobile" class="text-xs mt-1">{{ person.mobile }}</p></div><div><p class="tm-meta">{{ dayLabel(date) }} · shift</p><p class="tm-shift mt-1">{{ currentShift.map(r=>`${clock(r.starts_at)}–${clock(r.ends_at)}`).join(' · ') || 'No working hours set' }}</p><p class="tm-meta">{{ person.status==='active'?'Active team member':'Inactive team member' }} · {{ person.online_visible?'Visible online':'Hidden online' }}</p></div><p v-if="person.biography" class="tm-meta full">{{ person.biography }}</p></div>
     <section class="tm-profile-section"><h3>{{ dayLabel(date) }} appointments <span class="tm-meta">{{ appointments.length }}</span></h3><p v-if="!appointments.length" class="tm-meta">No appointments in the selected day.</p><div v-for="a in appointments" :key="a.id" class="tm-upcoming"><div><strong>{{ a.client_name }}</strong><small>{{ time(a.starts_at) }}–{{ time(a.ends_at) }} · {{ a.status.split('_').join(' ') }}</small></div><a v-if="can.calendar" :href="calendarUrl(localDate(Date.parse(a.starts_at),zone),a.id)" @click.prevent="navigate(calendarUrl(localDate(Date.parse(a.starts_at),zone),a.id))">Review <span aria-hidden="true">↗</span></a></div><p v-if="appointments.length===100" class="tm-meta mt-2">Showing the first 100 visits. Review the full Calendar.</p></section>
     <section class="tm-profile-section"><h3>Available booking gaps <span class="tm-meta">{{ dayLabel(date) }}</span></h3><p v-if="stale" class="tm-meta mb-2">Based on the last loaded schedule. Refresh availability before making assignment decisions.</p><p class="tm-meta mb-2">Free staff time. Calendar checks service duration, resources and booking rules.</p><p v-if="!bookingGaps.length" class="tm-meta">{{ state.state==='overrun'?'Finish or review the running visit before assigning another client.':'No remaining booking gaps.' }}</p><div v-for="g in bookingGaps" :key="g.startsAt" class="tm-upcoming"><strong>{{ time(g.startsAt) }}–{{ time(g.endsAt) }}</strong><a v-if="can.calendar" :href="calendarUrl()" @click.prevent="navigate(calendarUrl())">View calendar ↗</a></div></section>
     <section class="tm-profile-section"><h3>Upcoming shifts <span class="tm-meta">Next 4 days</span></h3><div v-for="d in upcomingShifts" :key="d.date" class="tm-upcoming"><span>{{ dayLabel(d.date) }}</span><strong>{{ d.off || d.rules.map(r=>`${clock(r.starts_at)}–${clock(r.ends_at)}`).join(' · ') || 'Off' }}</strong></div></section>
     <section class="tm-profile-section"><h3>Service capabilities <button type="button" @click="requestTab('services')">{{ person.can_edit?'Manage services':'View services' }}</button></h3><p class="tm-meta">{{ person.services.filter(s=>s.is_qualified && s.is_active).map(s=>s.name).join(' · ') || 'No services assigned yet.' }}</p></section>
     <section v-if="can.commission_all || (can.commission_own && can.own_staff===person.public_id)" class="tm-profile-section"><h3>Commissions & tips <button type="button" :disabled="statementBusy" @click="loadStatement">{{ statementBusy?'Loading…':'View period' }}</button></h3><p class="tm-meta">From completed sales, refunds and recorded adjustments.</p><p v-if="statementError" class="tm-error">{{ statementError }}</p><div v-if="statement" class="tm-meta mt-2"><p>{{ dayLabel(date.slice(0,7)+'-01') }}–{{ dayLabel(date) }} · {{ business.time_zone }}</p><div v-for="balance in statement.totals_by_currency || []" :key="balance.currency_code" class="mt-2"><p>Commission: {{ money(balance.commission_minor,balance.currency_code) }}</p><p>Tips: {{ money(balance.tips_minor,balance.currency_code) }}</p></div><p v-if="!statement.totals_by_currency?.length">No commission or tip entries in this period.</p><AppButton v-if="can.reports" variant="quiet" size="small" :href="route('business.reports.index',business.public_id)">Open Reports</AppButton></div></section>
    </template>
    <template v-else-if="tab==='schedule'">
     <p class="tm-meta mb-4">Regular hours repeat each week. Breaks and time off reduce bookable time. Temporary hours replace that day’s regular hours at the selected branch. Times use each branch’s timezone.</p>
     <template v-if="person.can_edit">
      <h3>Regular working hours</h3><div class="tm-schedule-tools"><AppSelect v-model="copyDay" class="cd-input" aria-label="Copy hours from day"><option v-for="(name,i) in dayNames" :key="i" :value="i+1">{{ name }}</option></AppSelect><button type="button" :disabled="!allRules(Number(copyDay)).length" @click="copyWeekdays">Copy to weekdays</button><button type="button" @click="useBranchHours">Use branch hours</button></div>
      <div class="tm-week-editor"><div v-for="(name,i) in dayNames" :key="i" class="tm-day-editor"><label class="tm-day-label"><input type="checkbox" :checked="allRules(i+1).length>0" @change="toggleDay(i+1,$event.target.checked)" />{{ name.slice(0,3) }}</label><div><p v-if="!allRules(i+1).length" class="tm-day-off">Off</p><div v-for="(r,j) in allRules(i+1)" :key="j" class="tm-day-controls"><div v-if="person.locations.length>1" class="tm-branch-select"><AppSelect v-model="r.location_id" class="cd-input" :aria-label="`${name} branch`"><option v-for="l in locations.filter(l=>person.locations.some(p=>p.public_id===l.public_id))" :key="l.id" :value="l.id">{{ l.name }}</option></AppSelect></div><input v-model="r.starts_at" type="time" class="cd-input" :aria-label="`${name} shift ${j+1} starts`" /><span class="tm-meta" aria-hidden="true">–</span><input v-model="r.ends_at" type="time" class="cd-input" :aria-label="`${name} shift ${j+1} ends`" /><button type="button" :aria-label="`Remove ${name} shift ${j+1}`" @click="removeRule(r)"><XMarkIcon /></button><button v-if="j===allRules(i+1).length-1" type="button" :aria-label="`Add split shift on ${name}`" @click="scheduleForm.rules.push({...newRule(i+1),starts_at:'18:00',ends_at:'20:00',sequence:j+2})"><PlusIcon /></button></div></div></div></div>
      <section class="tm-profile-section"><h3>Breaks & dated exceptions <button type="button" @click="openException('break')">Add break</button></h3><div class="flex gap-4 mb-3"><button type="button" class="tm-text-button" @click="openException('leave')"><PlusIcon />Time off</button><button type="button" class="tm-text-button" @click="openException('temporary_change')"><ClockIcon />Temporary hours</button></div><p v-if="!exceptions.length" class="tm-meta">No upcoming time off or breaks.</p><div v-for="(r,i) in exceptions" :key="i" class="tm-exception-row"><div><strong>{{ ruleLabel(r) }}</strong><small>{{ r.starts_on?`${dayLabel(r.starts_on)}${r.ends_on!==r.starts_on?' – '+dayLabel(r.ends_on):''}`:dayNames[r.day_of_week-1] }} · {{ r.starts_at?`${clock(r.starts_at)}–${clock(r.ends_at)}`:'Full day' }}<template v-if="locations.length>1"> · {{ locations.find(l=>l.id===r.location_id)?.name || 'All assigned branches' }}</template></small><small v-if="r.reason">{{ r.reason }}</small></div><button type="button" :aria-label="`Remove ${ruleLabel(r)} ${r.starts_on || dayNames[r.day_of_week-1]}`" @click="removeRule(r)">Remove</button></div></section>
      <div v-if="showException" class="tm-exception-editor"><h3>Add {{ ruleLabel(exception).toLocaleLowerCase() }}<button type="button" @click="showException=false">Cancel</button></h3><div class="tm-field-grid"><label>Type<AppSelect v-model="exception.kind" class="cd-input"><option value="leave">Time off / personal leave</option><option value="sick_leave">Sick leave</option><option value="holiday">Holiday</option><option value="break">Break</option><option value="temporary_change">Temporary working hours</option><option value="personal_block">Unavailable block</option></AppSelect></label><label>Branch<AppSelect v-model="exception.location_id" class="cd-input"><option v-if="exception.kind!=='temporary_change'" :value="null">All assigned branches</option><option v-for="l in locations.filter(l=>person.locations.some(p=>p.public_id===l.public_id))" :key="l.id" :value="l.id">{{ l.name }} · {{ l.time_zone }}</option></AppSelect></label><label v-if="['break','personal_block'].includes(exception.kind)">Repeat<AppSelect v-model="exception.recurrence" class="cd-input"><option value="dated">One-time / date range</option><option value="weekly">Every week</option></AppSelect></label><label v-if="['break','personal_block'].includes(exception.kind) && exception.recurrence==='weekly'">Day<AppSelect v-model="exception.day_of_week" class="cd-input"><option v-for="(name,i) in dayNames" :key="i" :value="i+1">{{ name }}</option></AppSelect></label><template v-else><label>From date<input v-model="exception.starts_on" type="date" class="cd-input" /></label><label>Through date<input v-model="exception.ends_on" type="date" class="cd-input" /></label></template><label v-if="isTimeOff(exception)" class="tm-check full"><input v-model="exception.full_day" type="checkbox" />Full day</label><template v-if="!isTimeOff(exception) || !exception.full_day"><label>Starts<input v-model="exception.starts_at" type="time" class="cd-input" /></label><label>Ends<input v-model="exception.ends_at" type="time" class="cd-input" /></label></template><label class="full">Private reason <span class="tm-meta">optional</span><input v-model="exception.reason" maxlength="255" class="cd-input" placeholder="Visible to authorized team managers" /></label><AppButton variant="secondary" class="full" @click="addException">Add to schedule review</AppButton></div></div>
      <div v-if="reviewError || Object.keys(scheduleForm.errors).length" class="tm-error" role="alert"><p v-if="reviewError">{{ reviewError }}</p><p v-for="(e,k) in scheduleForm.errors" :key="k">{{ e }}</p></div>
      <section v-if="review" class="tm-review" aria-live="polite"><h3 id="staff-impact-heading" tabindex="-1">{{ review.affected_count?`${review.affected_count} appointment${review.affected_count===1?'':'s'} affected`:'Ready to save' }}</h3><p>{{ review.affected_count?'These visits would fall outside the new availability. Review them before saving.':'No appointments outside the proposed availability. Calendar and Queue will use the updated hours.' }}</p><ul><li v-for="a in review.appointments" :key="a.id"><a target="_blank" rel="noopener" :href="route('business.calendar',{business:business.public_id,location:a.location,date:a.date,appointment:a.id,staff:[person.public_id],view:'staff'})">{{ dayLabel(a.date) }} · {{ time(a.starts_at,a.time_zone) }} · {{ a.location_name }} — review appointment</a></li></ul><p v-if="review.held_count" class="tm-error">{{ review.held_count }} active booking hold{{ review.held_count===1?'':'s' }} affected. Wait for completion or expiry, then review again.</p><template v-if="review.affected_count"><label class="tm-check"><input v-model="retained" type="checkbox" />Keep these appointments as explicit exceptions. I will manage them in Calendar.</label><label class="tm-block-label">Required reason<textarea v-model="scheduleForm.impact_reason" rows="2" class="cd-input" /></label></template><template v-if="review.outside_hours.length"><p class="mt-3 font-semibold">Some shifts extend beyond branch opening hours or special closures.</p><ul><li v-for="w in review.outside_hours" :key="w">{{ w }}</li></ul><label class="tm-check"><input v-model="hoursAcknowledged" type="checkbox" />Keep the entered hours. Actual bookability still respects branch opening hours and special closures.</label></template><p class="tm-meta mt-3">Review expires after 15 minutes. Appointments are rechecked when you save.</p></section>
     </template>
     <template v-else><h3>Weekly working hours</h3><div v-for="(name,i) in dayNames" :key="i" class="tm-upcoming"><span>{{ name }}</span><strong>{{ person.availability.filter(r=>r.kind==='working' && r.day_of_week===i+1).map(r=>`${clock(r.starts_at)}–${clock(r.ends_at)}`).join(' · ') || 'Off' }}</strong></div><section class="tm-profile-section"><h3>Breaks & time off</h3><p v-if="!person.availability.some(r=>r.kind!=='working')" class="tm-meta">No upcoming time off.</p><div v-for="(r,i) in person.availability.filter(r=>r.kind!=='working')" :key="i" class="tm-exception-row"><div><strong>{{ ruleLabel(r) }}</strong><small>{{ r.starts_on || dayNames[r.day_of_week-1] }} · {{ r.starts_at?`${clock(r.starts_at)}–${clock(r.ends_at)}`:'Full day' }}</small></div></div></section></template>
    </template>
    <template v-else-if="tab==='services'">
     <p class="tm-meta mb-4">Qualifications determine who can be assigned in Calendar and the Walk-in Queue. Duration includes active service time; processing and cleanup retain the service’s existing rules.</p>
     <template v-if="person.can_edit"><div class="tm-service-toolbar"><SearchField v-model="serviceSearch" label="Find a service" placeholder="Search services" /><button type="button" @click="selectCategory(serviceGroups.flatMap(g=>g.services),false)">Clear shown</button></div><section v-for="g in serviceGroups" :key="g.category" class="tm-service-category"><h3>{{ g.category }}<button type="button" @click="selectCategory(g.services,true)">Select shown</button></h3><div v-for="s in g.services" :key="s.public_id" class="tm-service-row"><div><label class="tm-check"><input type="checkbox" :checked="!!assignment(s)?.is_qualified" @change="toggleService(s,$event.target.checked)" />{{ s.name }}</label><small>{{ s.duration_minutes }} min · {{ money(s.price_minor,s.currency_code) }} standard</small><label v-if="assignment(s)?.is_qualified" class="tm-check"><input v-model="assignment(s).online_visible" type="checkbox" />Online booking</label></div><label>Duration (min)<input v-if="assignment(s)?.is_qualified" v-model.number="assignment(s).duration_minutes" type="number" min="1" max="1440" :placeholder="String(s.duration_minutes)" class="cd-input" :aria-label="`${s.name} duration override`" /><span v-else class="tm-meta">—</span></label><label>Price ({{ s.currency_code }})<input v-if="assignment(s)?.is_qualified" :value="priceDrafts[s.public_id] ?? (assignment(s).price_minor==null?'':moneyInput(assignment(s).price_minor,s.currency_code))" @input="setPrice(s,$event.target.value)" :aria-invalid="!!priceErrors[s.public_id]" type="number" :step="1/fraction(s.currency_code)" min="0" :placeholder="String(s.price_minor/fraction(s.currency_code))" class="cd-input" :aria-label="`${s.name} price override in ${s.currency_code}`" /><span v-else class="tm-meta">—</span></label></div></section><p v-for="(e,k) in priceErrors" :key="k" class="tm-error" role="alert">{{ e }}</p><p v-if="!serviceGroups.length" class="tm-meta mt-4">No services match your search.</p><label class="tm-block-label mt-5">Reason for removing a capability<textarea v-model="serviceForm.reason" class="cd-input" rows="2" placeholder="Required when future visits use a removed capability" /></label><div v-if="Object.keys(serviceForm.errors).length" class="tm-error" role="alert"><p v-for="(e,k) in serviceForm.errors" :key="k">{{ e }}</p></div></template>
     <template v-else><p v-if="!person.services.length" class="tm-meta">No services assigned.</p><div v-for="s in person.services" :key="s.public_id" class="tm-upcoming"><div><strong>{{ s.name }}</strong><small>{{ s.category }} · {{ s.is_qualified?'Qualified':'Not qualified' }}</small></div><span>{{ s.duration_minutes }} min</span></div></template>
    </template>
    <p v-else-if="tab==='access' && !person.can_edit" class="tm-meta">An owner or manager with access to every assigned branch can manage this person’s login.</p><AccessPanel v-else-if="tab==='access'" :person="person" :invitation="invitation" :business="business" :locations="locations" :roles="roles" :modules="modules" :grantable="grantable" :can-manage-owners="canManageOwners" @saved="saved" @dirty="accessDirty=$event" @busy="accessBusy=$event" />
   </div>
  </template>
  <template #footer><AppButton variant="secondary" @click="()=>{if(close())dialog?.close();}">Close</AppButton><template v-if="tab==='schedule' && person?.can_edit"><AppButton v-if="!review" :disabled="busy || !scheduleDirty || showException" :loading="reviewing" @click="preview">Review changes</AppButton><AppButton v-else :disabled="busy || review.held_count>0 || (review.affected_count>0 && (!retained || !scheduleForm.impact_reason.trim())) || (review.outside_hours.length>0 && !hoursAcknowledged)" @click="saveSchedule">{{ scheduleForm.processing?'Saving…':'Save reviewed schedule' }}</AppButton></template><AppButton v-if="tab==='services' && person?.can_edit" :disabled="!serviceForm.isDirty || serviceForm.processing || Object.keys(priceErrors).length>0" @click="saveServices">{{ serviceForm.processing?'Saving…':'Save capabilities' }}</AppButton></template>
 </AppDialog>
</template>
