<script setup>
import { computed } from 'vue';
import { CheckCircleIcon, ChevronRightIcon, GlobeAltIcon, ArrowRightIcon, ScissorsIcon, ClockIcon, UserGroupIcon, MapPinIcon, AdjustmentsHorizontalIcon, BuildingStorefrontIcon } from '@heroicons/vue/24/outline';
import AppButton from '@/Components/Product/AppButton.vue';
const props = defineProps({ summary:Object, business:Object, onboarding:Object, channels:Object });
const emit = defineEmits(['section','region']);
const icons = {profile:BuildingStorefrontIcon, location:MapPinIcon, services:ScissorsIcon, team:UserGroupIcon, availability:ClockIcon, booking_preferences:AdjustmentsHorizontalIcon};
const next = computed(() => props.summary.next);
const generated = computed(() => props.onboarding.generated_data || {});
const hasStarter = computed(() => Boolean(generated.value.version));
</script>
<template>
    <div class="bs-home">
        <section class="bs-readiness" aria-labelledby="setup-overview-title">
            <div class="bs-readiness-top"><span class="bs-eyebrow">YOUR BUSINESS, READY FOR THE DAY</span><span :class="['bs-status', summary.required_complete ? 'ready' : 'attention']"><CheckCircleIcon v-if="summary.required_complete" class="size-4" aria-hidden="true" />{{ summary.required_complete ? 'Essentials ready' : 'Setup in progress' }}</span></div>
            <div class="bs-readiness-body"><div><h2 id="setup-overview-title" tabindex="-1">{{ summary.required_complete ? 'You’re ready to take bookings.' : 'A few details. Then you’re ready.' }}</h2><p>{{ summary.required_complete ? 'Your services, team and working hours are connected. Start with your first appointment.' : 'A useful starting point is already here. Review what matters, at your own pace.' }}</p><p v-if="next" class="bs-next-label"><strong>Next: {{next.label}}</strong></p></div>
                <AppButton v-if="next" @click="emit('section',next.section)">Continue setup<ArrowRightIcon class="size-4" aria-hidden="true" /></AppButton><AppButton v-else :href="route('business.calendar',business.public_id)">Open calendar<ArrowRightIcon class="size-4" aria-hidden="true" /></AppButton>
            </div>
            <div class="bs-progress"><div class="bs-progress-segments" role="progressbar" aria-label="Operational essentials" :aria-valuenow="summary.completed" :aria-valuemax="summary.total" :aria-valuemin="0" :aria-valuetext="`${summary.completed} of ${summary.total} essentials ready`"><span v-for="task in summary.required" :key="task.id" :class="{done:task.complete}" /></div><strong>{{ summary.completed }} of {{ summary.total }} essentials ready</strong></div>
            <div class="bs-region"><span>{{ business.country_code || 'Choose country' }}</span><span>{{ business.currency_code || 'Choose currency' }}</span><span>{{ (business.time_zone || 'Choose time zone').replaceAll('_',' ') }}</span><button type="button" @click="emit('region')">Review region<ChevronRightIcon class="size-3" aria-hidden="true" /></button></div>
        </section>
        <div class="bs-home-grid"><section class="bs-panel" aria-labelledby="bs-essentials"><header class="bs-panel-heading"><div><h3 id="bs-essentials">The essentials</h3><p>Everything you need to run appointments.</p></div><span class="bs-muted">{{ summary.completed }}/{{ summary.total }}</span></header>
            <ol class="bs-checklist"><li v-for="task in summary.required" :key="task.id"><button type="button" @click="emit('section',task.section)"><span class="bs-task-icon"><component :is="icons[task.id]" class="size-5" aria-hidden="true" /></span><span class="bs-task-text"><strong>{{ task.label }}</strong><span>{{ task.description }}</span><small v-if="next?.id === task.id">Recommended next</small></span><span :class="['bs-status',task.complete?'ready':'attention']">{{ task.complete?'Ready':'Needs attention' }}</span><ChevronRightIcon class="bs-task-arrow size-4" aria-hidden="true" /></button></li></ol>
            <footer class="bs-panel-footer">Availability is checked against configured hours in the next four weeks. Calendar checks each appointment’s actual availability.</footer>
        </section>
        <aside class="bs-home-aside"><section class="bs-panel bs-starter"><header class="bs-panel-heading"><div><h3>{{ hasStarter ? 'Prepared for you' : 'Your current setup' }}</h3><p>{{ hasStarter ? 'Starter configuration, ready to personalize.' : 'We recognize what’s already configured.' }}</p></div></header>
            <dl><div><dt>Services</dt><dd>{{ hasStarter ? `${(generated.services || []).length} starter suggestions` : `${summary.counts.services} active services` }}</dd></div><div><dt>Opening hours</dt><dd>{{ hasStarter ? 'Starter week added' : `${summary.counts.locations} active location${summary.counts.locations===1?'':'s'}` }}</dd></div><div><dt>Team</dt><dd>{{ hasStarter && generated.owner_staff ? 'Your owner profile added' : `${summary.counts.staff} active members` }}</dd></div><div><dt>Calendar</dt><dd>{{ business.appointment_interval_minutes ? `${business.appointment_interval_minutes} minute intervals` : 'Choose an interval' }}</dd></div></dl>
            <p v-if="hasStarter" class="bs-note">Starter prices and hours are suggestions. Keep them, customize them or deactivate services you don’t offer. No clients or transactions were added.</p><AppButton variant="secondary" @click="emit('section','services')">Review your services<ScissorsIcon class="size-4" aria-hidden="true" /></AppButton>
        </section>
        <section class="bs-panel bs-online"><div class="bs-online-heading"><GlobeAltIcon class="size-5" aria-hidden="true" /><h3>Online booking</h3><span :class="['bs-status',summary.online_state==='Live'?'ready':'neutral']">{{ summary.online_state }}</span></div><p>{{ summary.online_state === 'Live' ? 'Your page is published. Review it before sharing your link.' : summary.required_complete ? 'Start taking appointments in Calendar. Go online when you’re ready.' : 'Finish the essentials, then choose when to go online.' }}</p><button type="button" class="bs-text-link" @click="emit('section','preview')">{{ summary.online_state === 'Live' ? 'Review booking page' : 'Preview & go live' }}<ArrowRightIcon class="size-4" aria-hidden="true" /></button></section></aside></div>
        <section class="bs-panel bs-optional" aria-labelledby="bs-optional-title"><header class="bs-panel-heading"><div><h3 id="bs-optional-title">Make it work your way</h3><p>Optional. Come back whenever you’re ready.</p></div><span class="bs-status neutral">Doesn’t block bookings</span></header><div class="bs-optional-grid"><button type="button" @click="emit('section','connections')"><strong>Payments & notifications</strong><span>Cash checkout is available. Email: {{ channels.email.toLowerCase() }}.</span><ChevronRightIcon class="size-4" aria-hidden="true" /></button><button type="button" @click="emit('section','branding')"><strong>Add your brand</strong><span>Logo, business photo and accent colour.</span><ChevronRightIcon class="size-4" aria-hidden="true" /></button><button type="button" @click="emit('section','import')"><strong>Bring your records</strong><span>Review a CSV before importing.</span><ChevronRightIcon class="size-4" aria-hidden="true" /></button></div></section>
    </div>
</template>
