<script setup>
import { ref, watch, onBeforeUnmount } from 'vue';
import { useForm } from '@inertiajs/vue3';
import axios from 'axios';
import AppButton from '@/Components/Product/AppButton.vue';
import AppDialog from '@/Components/Product/AppDialog.vue';
import FormField from '@/Components/Product/FormField.vue';
import { UserGroupIcon, ClockIcon } from '@heroicons/vue/24/outline';
const props=defineProps({business:Object,team:Array,locations:Array,canManage:Boolean});
const selected=ref(null),review=ref(null),busy=ref(false),error=ref(''),dialog=ref(null),notice=ref('');
const profileDialog=ref(null),profilePerson=ref(null),discardProfileDialog=ref(null);
const emit=defineEmits(['dirty']);
const profileForm=useForm({status:'active',online_visible:true,reason:''});
watch(()=>profileForm.isDirty,value=>emit('dirty',value));
onBeforeUnmount(()=>emit('dirty',false));
const canCloseProfile=()=>{if(profileForm.processing)return false;if(profileForm.isDirty){discardProfileDialog.value.open();return false;}return true;};
const discardProfile=()=>{profileForm.reset();profileDialog.value.close();};
const editProfile=person=>{profilePerson.value=person;profileForm.defaults({status:person.status,online_visible:person.online_visible,reason:''});profileForm.reset();profileForm.clearErrors();profileDialog.value.open();};
const saveProfile=()=>{const p=profilePerson.value;profileForm.transform(()=>({display_name:p.display_name,title:p.title,email:p.email,mobile:p.mobile,biography:p.biography,status:profileForm.status,online_visible:profileForm.online_visible,location_ids:p.locations.map(l=>l.public_id),profile_revision:p.profile_revision,reason:profileForm.reason})).patch(route('business.team.profile.update',[props.business.public_id,p.public_id]),{preserveScroll:true,onSuccess:()=>{profileForm.defaults();profileDialog.value.close();notice.value='Appointment availability saved. Login access stays as configured.';}});};
const form=useForm({rules:[],revision:'',impact_preview_id:'',impact_reason:''});
const prepare=async person=>{busy.value=true;error.value='';selected.value=person;const locationIds=person.locations.map(l=>l.id);const regular=props.locations.filter(l=>locationIds.includes(l.id)).flatMap(l=>l.hours.filter(h=>!h.effective_from && !h.effective_until).map(h=>({kind:'working',location_id:l.id,day_of_week:h.day_of_week,starts_at:h.opens_at.slice(0,5),ends_at:h.closes_at.slice(0,5),starts_on:null,ends_on:null,sequence:h.sequence,reason:null})));const retained=person.rules.filter(r=>r.kind!=='working');form.defaults({rules:[...regular,...retained],revision:person.revision,impact_preview_id:'',impact_reason:''});form.reset();form.clearErrors();try{const response=await axios.post(route('business.team.schedule.preview',[props.business.public_id,person.public_id]),{rules:form.rules,revision:form.revision});review.value=response.data;form.impact_preview_id=review.value.public_id;dialog.value.open();}catch(e){error.value=Object.values(e.response?.data?.errors||{}).flat().join(' ')||'We couldn’t review the working week. Try again.';}finally{busy.value=false;}};
const save=()=>form.put(route('business.team.schedule.update',[props.business.public_id,selected.value.public_id]),{preserveScroll:true,onSuccess:()=>{dialog.value.close();notice.value='Working hours copied. You can personalize them in Team & availability.';}});
</script>
<template>
    <section class="bs-panel"><header class="bs-panel-heading"><div><h2>Your team & availability</h2><p>Your owner profile is reused. Staff can work without needing a login.</p></div><AppButton :href="route('business.team.index',business.public_id)" variant="secondary" size="small">Team & availability</AppButton></header><p v-if="notice" class="bs-inline-success" role="status">{{notice}}</p><p v-if="error" class="bs-callout attention" role="alert">{{error}}</p>
        <div class="bs-team-list"><article v-for="person in team" :key="person.public_id" class="bs-team-row"><div class="bs-person"><span class="bs-avatar" aria-hidden="true">{{person.display_name.slice(0,1)}}</span><div><strong>{{person.display_name}}<small v-if="person.owner" class="bs-status neutral">Your owner profile</small></strong><span>{{person.title || 'Team member'}} · {{person.locations.map(l=>l.name).join(', ')||'Location needed'}}</span></div></div><div class="bs-team-facts"><span><UserGroupIcon class="size-4" aria-hidden="true" />{{person.service_count}} assigned services</span><span><ClockIcon class="size-4" aria-hidden="true" />{{person.rules.some(r=>r.kind==='working')?'Working week configured':'Working hours needed'}}</span><span class="bs-muted">{{person.status!=='active'?'Appointment availability paused':person.online_visible?'Shown on the booking page':'Hidden from online booking'}}</span></div><div v-if="person.locations.length && canManage" class="bs-team-actions"><AppButton variant="quiet" size="small" :disabled="busy || form.processing || profileForm.processing" @click="editProfile(person)">Appointment availability</AppButton><AppButton variant="secondary" size="small" :disabled="busy || form.processing || profileForm.processing" @click="prepare(person)">Use business hours</AppButton></div></article><div v-if="!team.length" class="bs-empty"><h3>Who takes appointments?</h3><p>Add yourself or your first professional. Assign their services and working hours.</p><AppButton :href="route('business.team.index',business.public_id)">Add a team member</AppButton></div></div><footer class="bs-panel-footer">Copied hours are a starting point, not a live link. Breaks and current time off are preserved. Assign services from Review services.</footer>
    </section>
    <AppDialog ref="profileDialog" title="Appointment availability" description="Pausing new appointments keeps this person’s login and existing visits. Services and working hours must also be configured." confirm-label="Save availability" :close-on-confirm="false" :confirm-disabled="profileForm.processing" :can-close="canCloseProfile" @confirm="saveProfile"><div class="bs-editor-fields"><label class="bs-checkbox"><input type="checkbox" :checked="profileForm.status==='active'" @change="profileForm.status=$event.target.checked?'active':'inactive'" />Allow new appointments</label><label class="bs-checkbox"><input v-model="profileForm.online_visible" type="checkbox" />Show this person on the online booking page</label><FormField id="bs-staff-availability-reason" label="Review reason" hint="Required when pausing a person who has upcoming appointments." :error="profileForm.errors.reason"><textarea id="bs-staff-availability-reason" v-model="profileForm.reason" rows="2" class="cd-input" /></FormField><p v-if="Object.keys(profileForm.errors).length" role="alert" class="bs-callout attention">{{Object.values(profileForm.errors).join(' ')}}</p></div></AppDialog>
    <AppDialog ref="discardProfileDialog" title="Discard unsaved availability changes?" description="Saved team settings stay as they are." confirm-label="Discard changes" @confirm="discardProfile" />
    <AppDialog ref="dialog" title="Use the business opening week?" description="This replaces regular working hours at this person’s assigned locations. Breaks and time off stay in place." confirm-label="Save working hours" :close-on-confirm="false" :confirm-disabled="form.processing" :can-close="()=>!form.processing" @confirm="save"><p class="bs-muted">{{review?.affected_count ? `${review.affected_count} appointments need review. Their booked times are retained.` : 'No existing appointments affected.'}}</p><FormField v-if="review?.affected_count" id="bs-team-reason" label="Reason for retaining existing appointments" required :error="form.errors.impact_reason"><textarea id="bs-team-reason" v-model="form.impact_reason" rows="2" class="cd-input" /></FormField><p v-if="Object.keys(form.errors).length" class="bs-callout attention" role="alert">{{Object.values(form.errors).join(' ')}}</p></AppDialog>
</template>
