<script setup>
import { computed, nextTick, ref, watch } from 'vue';
import { useForm } from '@inertiajs/vue3';
import axios from 'axios';
import { PlusIcon, XMarkIcon } from '@heroicons/vue/24/outline';
import AppButton from '@/Components/Product/AppButton.vue';
import AppSelect from '@/Components/Product/AppSelect.vue';
import FormField from '@/Components/Product/FormField.vue';
import { weekFromHours, hoursFromWeek, copyWeekdayHours } from '@/Support/businessSetup';
const props=defineProps({business:Object,locations:Array,revisions:Object});
const emit=defineEmits(['dirty']);
const selected=ref(props.locations[0]?.public_id||''), week=ref(weekFromHours(props.locations[0]?.hours||[])),baseline=ref(JSON.stringify(week.value)),review=ref(null),busy=ref(false),errors=ref({}),notice=ref(''),pending=ref(null);
const form=useForm({windows:[],revision:'',preview_id:'',reason:''});
const fieldError=(day,sequence,field)=>{let offset=0;for(const row of week.value){if(row.day_of_week===day)break;if(row.open)offset+=row.periods.length;}return errors.value[`windows.${offset+sequence}.${field}`];};
const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const dirty=computed(()=>JSON.stringify(week.value)!==baseline.value);
watch(dirty,v=>emit('dirty',v));
const location=computed(()=>props.locations.find(l=>l.public_id===selected.value));
const select=value=>{if(dirty.value){errors.value={location:'Save or discard this week before choosing another location.'};return;}selected.value=value;reset();};
const reset=()=>{week.value=weekFromHours(location.value?.hours||[]);baseline.value=JSON.stringify(week.value);review.value=null;pending.value=null;errors.value={};form.reset();emit('dirty',false);};
watch(()=>props.locations,()=>{if(!dirty.value)reset();});
watch(week,()=>{if(!form.processing){review.value=null;pending.value=null;}},{deep:true});
const preview=async()=>{busy.value=true;errors.value={};try{const payload={windows:hoursFromWeek(week.value),revision:props.revisions[selected.value]};const response=await axios.post(route('business.configuration.setup-hours.review',[props.business.public_id,selected.value]),payload);pending.value=payload;review.value=response.data;}catch(e){errors.value=e.response?.data?.errors||{review:'We couldn’t review these hours. Your changes are retained. Try again.'};await nextTick();document.querySelector('#bs-hours [aria-invalid="true"]')?.focus();}finally{busy.value=false;}};
const save=()=>{form.transform(()=>({...pending.value,preview_id:review.value.public_id,reason:form.reason})).put(route('business.configuration.setup-hours.save',[props.business.public_id,selected.value]),{preserveScroll:true,onSuccess:()=>{baseline.value=JSON.stringify(week.value);reset();notice.value='Business hours saved. Review staff working hours if your week changed.';},onError:()=>{errors.value=form.errors;}});};
const copy=day=>{week.value=copyWeekdayHours(week.value,day);};
const enabled=(day,on)=>{day.open=on;if(on && !day.periods.length)day.periods=[{opens_at:'09:00',closes_at:'18:00'}];};
</script>
<template>
    <section id="bs-hours" class="bs-panel"><header class="bs-panel-heading"><div><h2>Review your opening week</h2><p>Business hours say when you’re open. Each person’s working hours say when they can take appointments.</p></div><AppButton :href="route('business.locations.index',business.public_id)" variant="secondary" size="small">Location details</AppButton></header>
        <div v-if="!location" class="bs-empty"><h3>Add your first location</h3><p>We’ll use your business details as a starting point.</p><AppButton :href="route('business.locations.index',business.public_id)">Add location</AppButton></div>
        <template v-else><div class="bs-toolbar"><div v-if="locations.length===1"><strong>{{location.name}}</strong><span>{{location.time_zone.replaceAll('_',' ')}}</span></div><FormField v-else id="bs-hours-location" label="Location" :error="errors.location"><AppSelect id="bs-hours-location" :model-value="selected" @update:model-value="select"><option v-for="l in locations" :key="l.public_id" :value="l.public_id">{{l.name}}</option></AppSelect></FormField><span class="bs-status neutral">Local times</span></div>
        <p v-if="notice" class="bs-inline-success" role="status">{{notice}}</p>
        <div class="bs-week"><div v-for="(day,index) in week" :key="day.day_of_week" class="bs-day"><label class="bs-day-name"><input type="checkbox" :checked="day.open" :disabled="form.processing||busy" @change="enabled(day,$event.target.checked)" />{{days[index]}}</label><div class="bs-day-periods"><span v-if="!day.open" class="bs-closed">Closed</span><template v-else><div v-for="(period,sequence) in day.periods" :key="sequence" class="bs-time-period"><label><span class="ds-sr-only">{{days[index]}} period {{sequence+1}} opens</span><input :aria-invalid="fieldError(day.day_of_week,sequence,'opens_at')?true:undefined" :aria-describedby="fieldError(day.day_of_week,sequence,'opens_at')?'bs-hours-errors':undefined" v-model="period.opens_at" type="time" class="cd-input" :disabled="form.processing||busy" /></label><span aria-hidden="true">–</span><label><span class="ds-sr-only">{{days[index]}} period {{sequence+1}} closes</span><input :aria-invalid="fieldError(day.day_of_week,sequence,'closes_at')?true:undefined" :aria-describedby="fieldError(day.day_of_week,sequence,'closes_at')?'bs-hours-errors':undefined" v-model="period.closes_at" type="time" class="cd-input" :disabled="form.processing||busy" /></label><button v-if="day.periods.length>1" type="button" :aria-label="`Remove ${days[index]} period ${sequence+1}`" :disabled="form.processing||busy" @click="day.periods.splice(sequence,1)"><XMarkIcon class="size-4" aria-hidden="true" /></button></div><button v-if="day.periods.length<10" type="button" class="bs-text-link" :disabled="form.processing||busy" @click="day.periods.push({opens_at:'14:00',closes_at:'18:00'})"><PlusIcon class="size-3" aria-hidden="true" />Add period</button></template></div><button v-if="day.open && index<5" type="button" class="bs-copy" :disabled="form.processing||busy" @click="copy(day.day_of_week)">Copy to weekdays</button></div></div>
        <div id="bs-hours-errors" v-if="Object.keys(errors).length" class="bs-callout attention" role="alert">{{Object.values(errors).flat().join(' ')}}</div>
        <section v-if="review" class="bs-hours-review" aria-live="polite"><h3>{{review.count ? `${review.count} existing appointments to review` : 'No existing appointments affected'}}</h3><p>{{review.count?'These appointments will retain their booked times. Review them in Calendar before confirming.':'This regular week is ready to save. Staff working hours stay as configured.'}}</p><ul v-if="review.count"><li v-for="visit in review.appointments" :key="visit.public_id"><a :href="route('business.calendar',{business:business.public_id,appointment:visit.public_id})">{{new Intl.DateTimeFormat(business.locale||'en',{dateStyle:'medium',timeStyle:'short',timeZone:location.time_zone}).format(new Date(visit.starts_at_utc))}} · Open appointment</a></li></ul><FormField v-if="review.count" id="bs-hours-reason" label="Reason for retaining these appointments" required :error="form.errors.reason"><textarea id="bs-hours-reason" v-model="form.reason" class="cd-input" rows="2" /></FormField></section>
        <footer class="bs-save-bar"><span>{{form.processing?'Saving…':dirty?'Unsaved hours':'Your saved opening week'}}</span><div><AppButton variant="quiet" :disabled="!dirty||form.processing||busy" @click="reset">Discard changes</AppButton><AppButton v-if="!review" :loading="busy" :disabled="form.processing" @click="preview">Review hours</AppButton><AppButton v-else :loading="form.processing" @click="save">Save business hours</AppButton></div></footer></template>
    </section>
</template>
