<!doctype html>
<html lang="{{ str_replace('_', '-', $receiptLocale ?? 'en') }}">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Receipt {{ $receipt->receipt_number }}</title><style>@include('brand.document-styles') body{font-size:14px;max-width:680px;margin:2rem auto;padding:0 1.5rem}header{overflow-wrap:anywhere;border-bottom:2px solid #172554;padding-bottom:1rem}.meta{font-size:12px;color:#475569;line-height:1.8}.receipt-ref{overflow-wrap:anywhere}table{margin:1.5rem 0}.number{text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums}.total{font-weight:700;font-size:1.1rem}.print-action{font:inherit;border:1px solid #cbd5e1;background:white;border-radius:8px;padding:10px 16px;cursor:pointer;margin-bottom:20px}.print-action:focus-visible{outline:2px solid #4338ca;outline-offset:3px}.summary{margin-left:auto;max-width:360px}@media(max-width:420px){body{padding:0 1rem}table{font-size:12px}th,td{padding:8px 4px}.summary{max-width:none}}@media print{body{max-width:none;margin:0}.print-action{display:none}}</style></head>
<body>
@php
    $receiptTimeZone ??= 'UTC';
    $snapshot = $receipt->snapshot;
    $currency = data_get($snapshot, 'sale.currency_code', 'INR');
    $formatter = new NumberFormatter($receiptLocale ?? 'en', NumberFormatter::CURRENCY);
    $formatter->setTextAttribute(NumberFormatter::CURRENCY_CODE, $currency);
    $digits = $formatter->getAttribute(NumberFormatter::MAX_FRACTION_DIGITS);
    $format = fn ($minor) => $currency.' '.number_format(($minor ?? 0) / (10 ** $digits), $digits);
    $methodNames = ['cash' => 'Cash', 'card' => 'Card', 'upi' => 'UPI', 'bank_transfer' => 'Bank transfer', 'payment_link' => 'Payment link', 'custom' => 'Other'];
@endphp
<button class="print-action" type="button" onclick="window.print()">Print / save as PDF</button>
<header><span class="cd-document-label">{{ config('brand.product_name') }} receipt</span><h1 style="font-size:22px;margin:4px 0">{{ data_get($snapshot, 'business.name', config('brand.product_name')) }}</h1><span class="receipt-ref">Receipt {{ $receipt->receipt_number }}</span><br><small class="cd-document-muted">Issued {{ $receipt->issued_at->setTimezone($receiptTimeZone)->format('d M Y, H:i') }} {{ $receiptTimeZone }}</small></header>
@if(data_get($snapshot, 'client'))<p><strong>{{ $snapshot['client'] }}</strong><br><span class="meta">{{ data_get($snapshot, 'visit_reference') }} · {{ data_get($snapshot, 'location') }}</span></p>@endif
<table><thead><tr><th scope="col">Item</th><th scope="col">Qty</th><th scope="col" class="number">Unit price</th><th scope="col" class="number">Line total</th></tr></thead><tbody>@foreach(data_get($snapshot, 'lines', []) as $line)<tr><td>{{ $line['description'] }}@if($line['staff'] ?? null)<br><span class="meta">{{ $line['staff'] }}</span>@endif @if($line['discount_minor'] ?? 0)<br><span class="meta">Item discount −{{ $format($line['discount_minor']) }}</span>@endif</td><td>{{ $line['quantity'] }}</td><td class="number">{{ $format($line['unit_price_minor']) }}</td><td class="number">{{ isset($line['line_total_minor']) ? $format($line['line_total_minor']) : '—' }}</td></tr>@endforeach</tbody></table>
<table class="summary"><tbody><tr><td>Subtotal</td><td class="number">{{ $format(data_get($snapshot, 'sale.subtotal_minor')) }}</td></tr>@if(data_get($snapshot, 'sale.discount_minor', 0))<tr><td>Discount</td><td class="number">−{{ $format(data_get($snapshot, 'sale.discount_minor')) }}</td></tr>@endif @if(data_get($snapshot, 'sale.tax_minor', 0))<tr><td>{{ data_get($snapshot, 'tax_inclusive', false) ? 'Tax included' : 'Tax' }}</td><td class="number">{{ $format(data_get($snapshot, 'sale.tax_minor')) }}</td></tr>@endif @if(data_get($snapshot, 'sale.tip_minor', 0))<tr><td>Tips</td><td class="number">{{ $format(data_get($snapshot, 'sale.tip_minor')) }}</td></tr>@endif<tr class="total"><td>Sale total</td><td class="number">{{ $format(data_get($snapshot, 'sale.total_minor')) }}</td></tr>@if(data_get($snapshot, 'sale.deposit_applied_minor', 0))<tr><td>Deposit applied</td><td class="number">−{{ $format(data_get($snapshot, 'sale.deposit_applied_minor')) }}</td></tr>@endif<tr><td>Payments recorded</td><td class="number">{{ $format(data_get($snapshot, 'sale.paid_minor')) }}</td></tr>@if(data_get($snapshot, 'sale.refunded_minor', 0))<tr><td>Refunds / voids</td><td class="number">−{{ $format(data_get($snapshot, 'sale.refunded_minor')) }}</td></tr>@endif<tr class="total"><td>Balance due at issue</td><td class="number">{{ $format(data_get($snapshot, 'sale.balance_minor')) }}</td></tr></tbody></table>
@if(data_get($snapshot, 'payments'))<h2 style="font-size:16px">Payment history at issue</h2><table><thead><tr><th scope="col">Method</th><th scope="col">Entry</th><th scope="col" class="number">Amount</th></tr></thead><tbody>@foreach($snapshot['payments'] as $payment)<tr><td>{{ $methodNames[$payment['method']] ?? ucfirst(str_replace('_', ' ', $payment['method'])) }}</td><td>{{ ucfirst($payment['kind']) }}</td><td class="number">{{ $payment['kind'] === 'payment' ? '' : '−' }}{{ $format($payment['amount_minor']) }}</td></tr>@endforeach</tbody></table>@endif
<p class="meta">Keep this receipt for your records. This is the original issued receipt. Later adjustments remain in the sale history.</p>
</body></html>
