<!doctype html>
<html lang="en-IN">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Receipt {{ $receipt->receipt_number }}</title><style>body{font:14px system-ui,sans-serif;color:#1d2a25;max-width:680px;margin:2rem auto;padding:0 1.5rem}header{border-bottom:2px solid #1d5c47;padding-bottom:1rem}table{width:100%;border-collapse:collapse;margin:1.5rem 0}td,th{padding:.55rem 0;text-align:left;border-bottom:1px solid #dce4df}.number{text-align:right}.total{font-weight:700;font-size:1.1rem}@media print{body{margin:0;max-width:none}}</style></head>
<body>
<header><strong>{{ data_get($receipt->snapshot, 'business.name', 'Good Hours') }}</strong><br><span>Receipt {{ $receipt->receipt_number }}</span><br><small>Issued {{ $receipt->issued_at->setTimezone('Asia/Kolkata')->format('d M Y, H:i') }} IST</small></header>
<table><thead><tr><th>Item</th><th>Qty</th><th class="number">Amount</th></tr></thead><tbody>@foreach(data_get($receipt->snapshot, 'lines', []) as $line)<tr><td>{{ $line['description'] }}</td><td>{{ $line['quantity'] }}</td><td class="number">{{ data_get($receipt->snapshot, 'sale.currency_code') }} {{ number_format($line['unit_price_minor'] / 100, 2) }}</td></tr>@endforeach</tbody></table>
<table><tbody><tr><td>Tax</td><td class="number">{{ data_get($receipt->snapshot, 'sale.currency_code') }} {{ number_format(data_get($receipt->snapshot, 'sale.tax_minor', 0) / 100, 2) }}</td></tr><tr><td>Deposit applied</td><td class="number">- {{ data_get($receipt->snapshot, 'sale.currency_code') }} {{ number_format(data_get($receipt->snapshot, 'sale.deposit_applied_minor', 0) / 100, 2) }}</td></tr><tr class="total"><td>Total</td><td class="number">{{ data_get($receipt->snapshot, 'sale.currency_code') }} {{ number_format(data_get($receipt->snapshot, 'sale.total_minor', 0) / 100, 2) }}</td></tr></tbody></table>
<p>Keep this receipt for your records. Payment and tax details are reproduced from the immutable sale record.</p>
</body></html>
