<?php

return [
    'features' => [
        'online-booking' => [
            'label' => 'Online booking',
            'title' => 'Online booking that respects the working calendar',
            'description' => 'Give clients a focused mobile path while Good Hours keeps staff, service, resource and policy decisions in the same scheduling engine.',
            'definition' => 'Online booking in Good Hours is the client-facing use of the same availability, capacity-hold and booking-commit rules used by the front desk.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-07', 'FR-09', 'FR-10'],
            'workflow' => [
                ['title' => 'Show current choices', 'body' => 'Published locations, services, add-ons, eligible staff and policy are resolved from the Business configuration without exposing private schedules.'],
                ['title' => 'Hold the selected capacity', 'body' => 'A time selection creates an expiring hold over the same staff and resource capacity used by operational bookings.'],
                ['title' => 'Revalidate before confirmation', 'body' => 'The service snapshot, policy version and current capacity are checked again before one complete Appointment is committed.'],
                ['title' => 'Keep self-service purpose-bound', 'body' => 'Expiring secure links support view, reschedule, cancellation, contact, rebook, waitlist and payment status without using a booking reference as authentication.'],
            ],
            'proof' => [
                'Passwordless mobile booking with explicit service lines and local-time choices.',
                'Any-qualified and preferred-staff selection without private schedule details.',
                'Atomic waitlist claims that award an opening to one valid client.',
            ],
            'limitations' => [
                'Live deposit collection requires an approved and certified appointment-payment provider configuration.',
                'A booking Business must be published and reached with its specific slug; Good Hours does not operate a marketplace directory.',
            ],
            'related' => ['calendar-and-walk-ins', 'client-management'],
        ],
        'calendar-and-walk-ins' => [
            'label' => 'Calendar and walk-ins',
            'title' => 'Run booked appointments and walk-ins in one operational day',
            'description' => 'Coordinate staff time, required resources, appointment changes, blocks and the walk-in queue without bypassing the scheduling rules.',
            'definition' => 'The Good Hours calendar is an operational view over governed Appointment lifecycle and capacity commands, not a free-form grid that writes times directly.',
            'requirements' => ['FR-03', 'FR-05', 'FR-06', 'FR-07', 'FR-08'],
            'workflow' => [
                ['title' => 'See the day in useful views', 'body' => 'Today, day, week and staff-column views keep location, staff, service and status context available to the front desk.'],
                ['title' => 'Change work through controlled actions', 'body' => 'Move, resize, reassign, add or remove services, cancel, no-show, duplicate, rebook and block time through versioned commands.'],
                ['title' => 'Mix walk-ins with booked demand', 'body' => 'Queue estimates use current evidence, and conversion checks the assigned time, staff and capacity before service begins.'],
                ['title' => 'Recover from exceptions', 'body' => 'Late arrivals, overruns, unavailable staff and unexpected closures create explicit impact and recovery records.'],
            ],
            'proof' => [
                'Text, border and icon cues distinguish state without depending on colour.',
                'Optimistic versions reject stale edits instead of silently overwriting newer work.',
                'Manager overrides are limited to policy warnings; capacity conflicts remain non-overridable.',
            ],
            'limitations' => [
                'Search results are advisory; every change is revalidated when it is committed.',
                'The current conservative any-qualified locking strategy prioritises correctness over peak-traffic throughput.',
            ],
            'related' => ['online-booking', 'checkout-and-reporting'],
        ],
        'client-management' => [
            'label' => 'Client management',
            'title' => 'Keep useful client context without weakening consent or access',
            'description' => 'Bring visits, preferences, protected notes, forms, consent and attachments together with permission-aware history.',
            'definition' => 'Client management in Good Hours is a Business-owned service record linked to booking, communication and commerce history, with narrower access for sensitive context.',
            'requirements' => ['FR-11', 'FR-12', 'FR-13', 'FR-19'],
            'workflow' => [
                ['title' => 'Create or match conservatively', 'body' => 'Exact normalized identity can reuse a profile; spelling variations become review candidates rather than automatic fuzzy merges.'],
                ['title' => 'Keep authored service context', 'body' => 'Preferences, allergies, sensitivities, formulas, warnings and general notes retain authorship and protected access.'],
                ['title' => 'Request versioned forms', 'body' => 'Published templates freeze their wording and fields so a later edit cannot rewrite an earlier signed submission.'],
                ['title' => 'Track privacy work', 'body' => 'Export, correction, withdrawal and deletion/anonymisation requests have deadlines, review evidence and safe outcomes.'],
            ],
            'proof' => [
                'Private JPEG, PNG and PDF attachments use tenant-scoped storage and expiring access.',
                'Contact changes preserve history and rotate vulnerable future Appointment links.',
                'A merge previews and preserves relationships before selecting one survivor.',
            ],
            'limitations' => [
                'Destructive deletion/anonymisation is policy-blocked until OPEN-10 approves the final retention schedule and executor.',
                'Good Hours does not claim medical-record or healthcare regulatory compliance.',
            ],
            'related' => ['online-booking', 'checkout-and-reporting'],
        ],
        'checkout-and-reporting' => [
            'label' => 'Checkout and reporting',
            'title' => 'Close the service and keep the numbers explainable',
            'description' => 'Carry completed work into checkout, receipts, stock, commission and reports with append-only corrections and source-level drill-down.',
            'definition' => 'Checkout and reporting in Good Hours use completed Sale and Payment evidence as the common source for revenue, inventory, commission, tip and export projections.',
            'requirements' => ['FR-14', 'FR-15', 'FR-16', 'FR-17', 'FR-18'],
            'workflow' => [
                ['title' => 'Build checkout from the appointment', 'body' => 'Service, add-on and product lines carry explicit tax, discount, tip, deposit and balance context into one Sale.'],
                ['title' => 'Record real tender outcomes', 'body' => 'Cash, card, UPI, bank transfer, payment link, custom and pay-later methods support partial or split payment evidence.'],
                ['title' => 'Correct without erasing', 'body' => 'Refunds, voids, deposit changes, cash-close adjustments and commission offsets create compensating history.'],
                ['title' => 'Trace totals to their source', 'body' => 'Dashboard, report, CSV and printable views use versioned definitions and drill to completed Sale and Payment records.'],
            ],
            'proof' => [
                'Location-day and currency context stay explicit across receipt, close and report output.',
                'Completed retail lines deduct stock exactly once and refunds require a physical disposition.',
                'Queued exports snapshot Business, Membership, filters and permission scope before execution.',
            ],
            'limitations' => [
                'Live appointment card processing and settlement reconciliation remain blocked pending provider certification.',
                'Inventory is lightweight; procurement, supplier and warehouse-transfer workflows are not Phase 1.',
            ],
            'related' => ['calendar-and-walk-ins', 'client-management'],
        ],
    ],
    'solutions' => [
        'barbershops' => [
            'label' => 'Barbershops',
            'title' => 'Barbershop software for booked clients and the walk-in line',
            'description' => 'Keep fast services, walk-ins, staff columns, client context and checkout in one front-desk day.',
            'fit' => 'Good Hours fits barbershops that need to balance appointments with walk-in demand without treating the queue as a separate spreadsheet or whiteboard.',
            'requirements' => ['FR-04', 'FR-05', 'FR-06', 'FR-08', 'FR-11', 'FR-14', 'FR-15'],
            'challenges' => [
                ['title' => 'The next walk-in cannot break the next booking', 'body' => 'Queue estimates and assignment use current staff and appointment evidence before a walk-in becomes service work.'],
                ['title' => 'A fast chair still needs a clear record', 'body' => 'Booked and walk-in visits connect service lines, staff attribution, notes, checkout and receipt history.'],
                ['title' => 'The front desk needs one view of exceptions', 'body' => 'Late arrivals, overruns, unavailable staff and unexpected closures stay explicit and recoverable.'],
            ],
            'day' => ['Capture a walk-in with the requested service', 'Estimate and order the queue with a recorded reason', 'Assign staff without colliding with booked work', 'Start service, check out and retain actual wait history'],
            'features' => ['calendar-and-walk-ins', 'checkout-and-reporting', 'client-management'],
            'limits' => ['Good Hours does not promise a wait time before current operating evidence exists.', 'No marketplace or local barbershop directory is included.'],
        ],
        'salons' => [
            'label' => 'Salons',
            'title' => 'Salon software that carries multi-service work through the day',
            'description' => 'Coordinate service timing, staff handoffs, client preferences, booking policy and checkout without splitting the visit into disconnected records.',
            'fit' => 'Good Hours fits appointment-led hair and beauty salons whose services can include different staff, add-ons, processing time and durable client context.',
            'requirements' => ['FR-04', 'FR-05', 'FR-06', 'FR-07', 'FR-09', 'FR-11', 'FR-12', 'FR-14'],
            'challenges' => [
                ['title' => 'One visit can contain more than one service', 'body' => 'Service lines retain their own duration, staff eligibility, processing and cleanup segments inside one Appointment.'],
                ['title' => 'Client context needs the right visibility', 'body' => 'Preferences, formulas, sensitivities, forms and warnings stay authored and permission-aware.'],
                ['title' => 'Changes must preserve what the client saw', 'body' => 'Policy, service and price snapshots keep later configuration edits from rewriting the booked visit.'],
            ],
            'day' => ['Publish qualified services and current availability', 'Carry a multi-line appointment into the team calendar', 'Record protected client context during service', 'Apply the deposit and complete a traceable checkout'],
            'features' => ['online-booking', 'calendar-and-walk-ins', 'client-management'],
            'limits' => ['Live deposits remain subject to appointment-payment provider approval.', 'Memberships, packages, loyalty and automated marketing campaigns are not Phase 1.'],
        ],
        'independent-stylists' => [
            'label' => 'Independent stylists',
            'title' => 'A simpler operating system for an independent stylist',
            'description' => 'Move from guided setup to booking, the working calendar, client history and checkout without needing a separate admin team.',
            'fit' => 'Good Hours fits an independent professional who owns the Business and performs the work, while keeping the same permissions and history ready for a future team.',
            'requirements' => ['FR-01', 'FR-02', 'FR-04', 'FR-05', 'FR-09', 'FR-11', 'FR-14', 'FR-18'],
            'challenges' => [
                ['title' => 'Setup needs to show what is truly missing', 'body' => 'Readiness names blocking details, hours, services, availability and policy instead of hiding them behind a percentage.'],
                ['title' => 'The calendar should not require constant reconciliation', 'body' => 'Public and owner-created bookings use the same staff and resource capacity checks.'],
                ['title' => 'A small business still needs explainable history', 'body' => 'Receipts, payments, client visits and reports remain linked without deleting corrections.'],
            ],
            'day' => ['Complete guided readiness and preview the booking page', 'Share the Business-specific booking link', 'Work from one calendar and client record', 'Close the Sale and review the local-day totals'],
            'features' => ['online-booking', 'client-management', 'checkout-and-reporting'],
            'limits' => ['Good Hours does not provide a marketing marketplace or guarantee new client demand.', 'The launch profile is web-first; there is no native mobile app.'],
        ],
        'spas' => [
            'label' => 'Small spas',
            'title' => 'Spa scheduling that reserves the room as well as the practitioner',
            'description' => 'Coordinate qualified staff, rooms or equipment, multi-segment treatments and consultation evidence with explicit limits.',
            'fit' => 'Good Hours fits small non-medical spas that need appointment and physical-resource capacity to be committed together.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-07', 'FR-11', 'FR-12'],
            'challenges' => [
                ['title' => 'A free practitioner is not enough', 'body' => 'Configured rooms or equipment can have quantities, opening hours and maintenance that participate in the same capacity decision.'],
                ['title' => 'Treatments may include active and processing time', 'body' => 'Service segments can release or change provider responsibility while keeping the complete visit atomic.'],
                ['title' => 'Consultation evidence must not drift', 'body' => 'Published form wording and submitted answers remain frozen to the appointment and template version.'],
            ],
            'day' => ['Resolve current treatment duration and required resources', 'Offer only capacity that fits staff and the room', 'Collect a versioned pre-appointment form when configured', 'Preserve the visit, submission and checkout context together'],
            'features' => ['online-booking', 'calendar-and-walk-ins', 'client-management'],
            'limits' => ['Good Hours does not claim HIPAA, medical-device or healthcare regulatory compliance.', 'Complex medical workflows, classes and facility-wide resource optimisation are not Phase 1.'],
        ],
    ],
    'use_cases' => [
        'reduce-scheduling-conflicts' => [
            'label' => 'Reduce scheduling conflicts',
            'title' => 'Reduce scheduling conflicts by checking the same capacity twice',
            'description' => 'Use one availability model for client booking and front-desk changes, then revalidate staff, service and resource capacity before committing the appointment.',
            'answer' => 'Scheduling conflicts are best reduced by making every booking path use the same working hours, staff eligibility, service duration and resource rules. Good Hours searches those rules, places a short capacity hold and checks them again at confirmation; it helps prevent conflicts but cannot eliminate incorrect configuration or real-world disruption.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-07'],
            'symptoms' => ['A client sees a time the front desk believes is unavailable.', 'A room or piece of equipment is promised to two services.', 'A late edit silently overwrites a newer calendar change.'],
            'practice' => [
                ['title' => 'Write down the real constraints', 'body' => 'Keep location hours, staff working intervals, breaks, service segments, cleanup time and required resource quantities current.'],
                ['title' => 'Use one booking path', 'body' => 'Create public, front-desk and moved appointments through the same availability and capacity commands rather than adjusting calendar timestamps directly.'],
                ['title' => 'Recheck at the decision point', 'body' => 'Treat search results as advisory and validate the selected slot again when it is held and confirmed.'],
                ['title' => 'Review exceptions as operating evidence', 'body' => 'Record late arrivals, overruns, closures and unavailable staff so the team can recover without disguising the original plan.'],
            ],
            'product_steps' => ['Resolve eligible staff and resources without exposing private schedules.', 'Create an expiring capacity hold for the chosen slot.', 'Lock and revalidate the appointment version before commit.', 'Reject stale or conflicting changes with a clear recovery path.'],
            'limitations' => ['Good configuration still matters: outdated hours, eligibility or resource quantities can make otherwise-correct results unhelpful.', 'Unexpected closures and service overruns require an explicit recovery decision; software cannot guarantee a conflict-free day.'],
            'feature' => 'calendar-and-walk-ins',
            'solution' => 'salons',
        ],
        'manage-walk-ins-and-appointments' => [
            'label' => 'Manage walk-ins and appointments',
            'title' => 'Manage walk-ins without losing sight of booked appointments',
            'description' => 'Capture the queue, explain the estimate and revalidate capacity before a walk-in becomes an appointment on the working calendar.',
            'answer' => 'Booked appointments and walk-ins can share one operating view when the queue remains a request—not a hidden calendar reservation—until staff and time are assigned. Good Hours keeps queue evidence beside the calendar and validates capacity when the walk-in is converted.',
            'requirements' => ['FR-06', 'FR-08'],
            'symptoms' => ['A verbal queue estimate competes with the next booked client.', 'The team cannot tell why one walk-in moved ahead of another.', 'Actual waits disappear, leaving future estimates to guess.'],
            'practice' => [
                ['title' => 'Capture the request consistently', 'body' => 'Record arrival, requested service, preferred or any qualified staff, and the client\'s notification choice.'],
                ['title' => 'Explain the queue order', 'body' => 'Use a visible ordering reason and treat estimated start time as changeable operating guidance.'],
                ['title' => 'Check the real calendar before assignment', 'body' => 'Confirm the service still fits around booked work and staff capacity at the moment of conversion.'],
                ['title' => 'Retain the actual outcome', 'body' => 'Keep served, cancelled, no-response and walk-out outcomes plus actual wait evidence for later review.'],
            ],
            'product_steps' => ['Add a walk-in with service and staff preference.', 'Review the evidence-based estimate and queue order.', 'Assign staff and revalidate capacity atomically.', 'Start service and preserve the queue-to-appointment history.'],
            'limitations' => ['A wait estimate is not a promise and should change when current work, staffing or service choice changes.', 'A walk-in cannot override a real staff or resource conflict; a manager may override policy warnings only.'],
            'feature' => 'calendar-and-walk-ins',
            'solution' => 'barbershops',
        ],
        'protect-time-with-deposits' => [
            'label' => 'Protect time with deposits',
            'title' => 'Use deposits as one part of a clear booking policy',
            'description' => 'Show the current deposit and cancellation terms before confirmation, preserve the accepted policy version and apply completed payment evidence at checkout.',
            'answer' => 'A deposit can help protect reserved time when the amount, due point, cancellation terms and refund handling are clear. Good Hours can calculate and snapshot configured policy, but live collection depends on an approved payment provider and no deposit guarantees attendance.',
            'requirements' => ['FR-09', 'FR-10', 'FR-14'],
            'symptoms' => ['Clients do not see the cancellation terms until after booking.', 'A policy edit appears to change an older appointment.', 'The front desk cannot trace a deposit into the final balance or refund.'],
            'practice' => [
                ['title' => 'Choose a proportionate rule', 'body' => 'Decide which services require a deposit, how it is calculated and what happens after cancellation or no-show, with appropriate legal review.'],
                ['title' => 'Show the terms before consent', 'body' => 'Present the amount and cancellation policy in the booking flow before confirmation rather than relying on a later message.'],
                ['title' => 'Preserve what was accepted', 'body' => 'Snapshot the policy version and deposit requirement so future configuration edits do not rewrite the agreement.'],
                ['title' => 'Reconcile the money', 'body' => 'Link successful, failed, refunded or waived deposit evidence to the appointment and final Sale without deleting corrections.'],
            ],
            'product_steps' => ['Resolve the published policy for the booking context.', 'Display and snapshot the deposit requirement before confirmation.', 'Accept provider callbacks idempotently when live collection is enabled.', 'Apply completed deposit evidence to checkout and record later corrections.'],
            'limitations' => ['Live appointment payment collection is not launch-ready until Stripe provider approval, webhook and settlement certification are complete.', 'Good Hours does not guarantee that deposits reduce no-shows or supply legal advice about cancellation terms.'],
            'feature' => 'online-booking',
            'solution' => 'independent-stylists',
        ],
        'keep-client-history-together' => [
            'label' => 'Keep client history together',
            'title' => 'Keep useful client history connected to the service record',
            'description' => 'Connect visits, preferences, protected notes, forms, consent, messages and purchases while keeping sensitive context permission-aware.',
            'answer' => 'A useful client history connects service and commerce records without turning every note into public team context. Good Hours keeps one Business-owned profile with authored, permission-aware records and conservative matching rather than silently merging similar people.',
            'requirements' => ['FR-11', 'FR-12', 'FR-13', 'FR-14', 'FR-19'],
            'symptoms' => ['Preferences and formulas live in personal notes that the next authorised professional cannot find.', 'Duplicate profiles split visits and receipts across identities.', 'A contact update loses the earlier audit trail or weakens secure links.'],
            'practice' => [
                ['title' => 'Collect only useful context', 'body' => 'Define why each field or note is needed, who can see it and how long it should remain.'],
                ['title' => 'Separate general from protected notes', 'body' => 'Use narrower access for sensitivities, formulas, warnings and consultation evidence instead of sharing everything equally.'],
                ['title' => 'Match and merge conservatively', 'body' => 'Reuse exact normalized identity where safe; review possible duplicates and preview all relationships before merging.'],
                ['title' => 'Preserve requests and changes', 'body' => 'Track consent, contact changes and privacy cases with authorship and deadlines rather than erasing the evidence.'],
            ],
            'product_steps' => ['Open the Business-owned client profile from the appointment.', 'Review visits, forms and protected notes within current permission scope.', 'Carry completed service and Sale context into history.', 'Audit identity changes, merges and privacy-request outcomes.'],
            'limitations' => ['Final destructive deletion and anonymisation remain blocked until OPEN-10 approves the retention schedule and executor.', 'Good Hours is not a medical-record system and does not claim healthcare regulatory compliance.'],
            'feature' => 'client-management',
            'solution' => 'spas',
        ],
    ],
    'guides' => [
        'booking-policy-basics' => [
            'title' => 'Booking policy basics for a clearer client decision',
            'description' => 'A practical framework for making booking, deposit, cancellation and change terms visible and operable.',
            'topic' => 'Booking policy', 'published_at' => '2026-08-16', 'reviewed_by' => 'Good Hours Product and Engineering',
            'intro' => 'A useful booking policy tells clients what is reserved, what may be charged, when changes are allowed and how exceptions are handled. It should match the team’s actual operating process and receive appropriate legal review.',
            'sections' => [
                ['title' => 'Start with the operating decision', 'body' => 'List which services, staff or lead times need special handling. Avoid copying a stricter policy that the team cannot apply consistently.'],
                ['title' => 'Put terms before confirmation', 'body' => 'Show deposit amount, cancellation window and important exceptions before the client confirms—not only in a later reminder.'],
                ['title' => 'Preserve the accepted version', 'body' => 'Keep the policy version and calculation attached to the appointment so a later edit does not rewrite an earlier agreement.'],
                ['title' => 'Design the exception path', 'body' => 'Define who may waive a deposit or policy warning, which reason is recorded and how a refund or checkout correction remains traceable.'],
            ],
            'checklist' => ['Services and circumstances covered', 'Deposit calculation and due point', 'Cancellation/reschedule window', 'Late/no-show handling', 'Refund/waiver authority and reason', 'Client-visible contact or recovery path', 'Legal and operations approval date'],
            'limitation' => 'This guide is general operating guidance, not legal advice. Live deposit collection in Good Hours remains provider-qualified.',
            'feature' => 'online-booking',
        ],
        'salon-opening-checklist' => [
            'title' => 'A salon opening checklist grounded in the working day',
            'description' => 'Prepare the minimum business, location, service, staff and booking rules needed before sharing an online booking link.',
            'topic' => 'Salon setup', 'published_at' => '2026-08-16', 'reviewed_by' => 'Good Hours Product and Engineering',
            'intro' => 'Opening readiness is clearer when it names each blocking operating fact instead of hiding the work behind a percentage. Complete the facts your calendar and clients depend on first.',
            'sections' => [
                ['title' => 'Define the Business and location day', 'body' => 'Confirm display name, time zone, currency, address/contact context and the local opening intervals that determine bookable time.'],
                ['title' => 'Make services schedulable', 'body' => 'Give each service an accurate duration, price, eligible staff and any processing, cleanup, add-on or physical-resource requirement.'],
                ['title' => 'Make staff availability explicit', 'body' => 'Record each person’s location assignment, working intervals, breaks and service eligibility before relying on public availability.'],
                ['title' => 'Preview before publishing', 'body' => 'Review policy, booking questions and client-facing choices with synthetic bookings, then publish the Business-specific booking route only when the blockers are clear.'],
            ],
            'checklist' => ['Business name, time zone and currency', 'Location details and weekly hours', 'Service duration, price and eligibility', 'Staff assignments, hours and breaks', 'Resource quantities where needed', 'Booking/deposit/cancellation policy', 'Owner preview and readiness review'],
            'limitation' => 'This checklist does not replace tax, employment, licensing, safety, insurance or privacy advice for a specific salon.',
            'feature' => 'calendar-and-walk-ins',
        ],
    ],
];
