<?php

return [
    'features' => [
        'online-booking' => [
            'label' => 'Online booking',
            'seo_title' => 'Online booking software for service businesses | ClipperDesk',
            'image' => '/images/marketing/editorial/use-cases-front-desk.webp',
            'title' => 'Online booking that respects the working calendar',
            'description' => 'Give clients a focused mobile path while ClipperDesk keeps staff, service, resource and policy decisions in the same scheduling engine.',
            'definition' => 'Online booking in ClipperDesk is the client-facing use of the same availability, capacity-hold and booking-commit rules used by the front desk.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-07', 'FR-09', 'FR-10'],
            'workflow' => [
                ['title' => 'Show current choices', 'body' => 'Published locations, services, add-ons, eligible staff and policy are resolved from the Business configuration without exposing private schedules.'],
                ['title' => 'Hold the selected capacity', 'body' => 'A time selection creates an expiring hold over the same staff and resource capacity used by operational bookings.'],
                ['title' => 'Revalidate before confirmation', 'body' => 'The service snapshot, policy version and current capacity are checked again before one complete Appointment is committed.'],
                ['title' => 'Keep self-service purpose-bound', 'body' => 'Expiring secure links support view, reschedule, cancellation, contact, rebook, waitlist and payment status without using a booking reference as authentication.'],
            ],
            'proof' => [
                'Passwordless mobile booking with explicit service lines and local-time choices.',
                'Any-qualified and preferred-staff selection without private schedule details.',
                'Atomic waitlist claims that award an opening to one valid client.',
            ],
            'limitations' => [
                'Live deposit collection requires an approved and certified appointment-payment provider configuration.',
                'A booking Business must be published and reached with its specific slug; ClipperDesk does not operate a marketplace directory.',
            ],
            'related' => ['calendar-and-walk-ins', 'client-management'],
        ],
        'calendar-and-walk-ins' => [
            'label' => 'Calendar and walk-ins',
            'seo_title' => 'Calendar and walk-in software for service businesses | ClipperDesk',
            'image' => '/images/marketing/industries/barbershop.webp',
            'title' => 'Run booked appointments and walk-ins in one operational day',
            'description' => 'Coordinate staff time, required resources, appointment changes, blocks and the walk-in queue without bypassing the scheduling rules.',
            'definition' => 'The ClipperDesk calendar is an operational view over governed Appointment lifecycle and capacity commands, not a free-form grid that writes times directly.',
            'requirements' => ['FR-03', 'FR-05', 'FR-06', 'FR-07', 'FR-08'],
            'workflow' => [
                ['title' => 'See the day in useful views', 'body' => 'Today, day, week and staff-column views keep location, staff, service and status context available to the front desk.'],
                ['title' => 'Change work through controlled actions', 'body' => 'Move, resize, reassign, add or remove services, cancel, no-show, duplicate, rebook and block time through versioned commands.'],
                ['title' => 'Mix walk-ins with booked demand', 'body' => 'Queue estimates use current evidence, and conversion checks the assigned time, staff and capacity before service begins.'],
                ['title' => 'Recover from exceptions', 'body' => 'Late arrivals, overruns, unavailable staff and unexpected closures create explicit impact and recovery records.'],
            ],
            'proof' => [
                'Text, border and icon cues distinguish state without depending on colour.',
                'Optimistic versions reject stale edits instead of silently overwriting newer work.',
                'Manager overrides are limited to policy warnings; capacity conflicts remain non-overridable.',
            ],
            'limitations' => [
                'Search results are advisory; every change is revalidated when it is committed.',
                'The current conservative any-qualified locking strategy prioritises correctness over peak-traffic throughput.',
            ],
            'related' => ['online-booking', 'checkout-and-reporting'],
        ],
        'client-management' => [
            'label' => 'Client management',
            'seo_title' => 'Client management software for service businesses | ClipperDesk',
            'image' => '/images/marketing/industries/nail-salon.webp',
            'title' => 'Keep useful client context without weakening consent or access',
            'description' => 'Bring visits, preferences, protected notes, forms, consent and attachments together with permission-aware history.',
            'definition' => 'Client management in ClipperDesk is a Business-owned service record linked to booking, communication and commerce history, with narrower access for sensitive context.',
            'requirements' => ['FR-11', 'FR-12', 'FR-13', 'FR-19'],
            'workflow' => [
                ['title' => 'Create or match conservatively', 'body' => 'Exact normalized identity can reuse a profile; spelling variations become review candidates rather than automatic fuzzy merges.'],
                ['title' => 'Keep authored service context', 'body' => 'Preferences, allergies, sensitivities, formulas, warnings and general notes retain authorship and protected access.'],
                ['title' => 'Request versioned forms', 'body' => 'Published templates freeze their wording and fields so a later edit cannot rewrite an earlier signed submission.'],
                ['title' => 'Track privacy work', 'body' => 'Export, correction, withdrawal and deletion/anonymisation requests have deadlines, review evidence and safe outcomes.'],
            ],
            'proof' => [
                'Private JPEG, PNG and PDF attachments use tenant-scoped storage and expiring access.',
                'Contact changes preserve history and rotate vulnerable future Appointment links.',
                'A merge previews and preserves relationships before selecting one survivor.',
            ],
            'limitations' => [
                'Destructive deletion/anonymisation is policy-blocked until OPEN-10 approves the final retention schedule and executor.',
                'ClipperDesk does not claim medical-record or healthcare regulatory compliance.',
            ],
            'related' => ['online-booking', 'checkout-and-reporting'],
        ],
        'checkout-and-reporting' => [
            'label' => 'Checkout and reporting',
            'seo_title' => 'Checkout and reporting for service businesses | ClipperDesk',
            'image' => '/images/marketing/editorial/pricing-decision.webp',
            'title' => 'Close the service and keep the numbers explainable',
            'description' => 'Carry completed work into checkout, receipts, stock, commission and reports with append-only corrections and source-level drill-down.',
            'definition' => 'Checkout and reporting in ClipperDesk use completed Sale and Payment evidence as the common source for revenue, inventory, commission, tip and export projections.',
            'requirements' => ['FR-14', 'FR-15', 'FR-16', 'FR-17', 'FR-18'],
            'workflow' => [
                ['title' => 'Build checkout from the appointment', 'body' => 'Service, add-on and product lines carry explicit tax, discount, tip, deposit and balance context into one Sale.'],
                ['title' => 'Record real tender outcomes', 'body' => 'Cash, card, UPI, bank transfer, payment link, custom and pay-later methods support partial or split payment evidence.'],
                ['title' => 'Correct without erasing', 'body' => 'Refunds, voids, deposit changes, cash-close adjustments and commission offsets create compensating history.'],
                ['title' => 'Trace totals to their source', 'body' => 'Dashboard, report, CSV and printable views use versioned definitions and drill to completed Sale and Payment records.'],
            ],
            'proof' => [
                'Location-day and currency context stay explicit across receipt, close and report output.',
                'Completed retail lines deduct stock exactly once and refunds require a physical disposition.',
                'Queued exports snapshot Business, Membership, filters and permission scope before execution.',
            ],
            'limitations' => [
                'Live appointment card processing and settlement reconciliation remain blocked pending provider certification.',
                'Inventory is lightweight; procurement, supplier and warehouse-transfer workflows are not Phase 1.',
            ],
            'related' => ['calendar-and-walk-ins', 'client-management'],
        ],
    ],
    'solutions' => [
        'barbershops' => [
            'label' => 'Barbershops',
            'seo_title' => 'Barbershop scheduling and walk-in software | ClipperDesk',
            'title' => 'Barbershop software for booked clients and the walk-in line',
            'description' => 'Keep fast services, walk-ins, staff columns, client context and checkout in one front-desk day.',
            'image' => '/images/marketing/industries/barbershop.webp',
            'image_alt' => 'A barber giving a precise haircut in a busy modern barbershop',
            'accent' => 'cobalt',
            'fit' => 'ClipperDesk fits barbershops that need to balance appointments with walk-in demand without treating the queue as a separate spreadsheet or whiteboard.',
            'requirements' => ['FR-04', 'FR-05', 'FR-06', 'FR-08', 'FR-11', 'FR-14', 'FR-15'],
            'challenges' => [
                ['title' => 'The next walk-in cannot break the next booking', 'body' => 'Queue estimates and assignment use current staff and appointment evidence before a walk-in becomes service work.'],
                ['title' => 'A fast chair still needs a clear record', 'body' => 'Booked and walk-in visits connect service lines, staff attribution, notes, checkout and receipt history.'],
                ['title' => 'The front desk needs one view of exceptions', 'body' => 'Late arrivals, overruns, unavailable staff and unexpected closures stay explicit and recoverable.'],
            ],
            'day' => ['Capture a walk-in with the requested service', 'Estimate and order the queue with a recorded reason', 'Assign staff without colliding with booked work', 'Start service, check out and retain actual wait history'],
            'features' => ['calendar-and-walk-ins', 'checkout-and-reporting', 'client-management'],
            'limits' => ['ClipperDesk does not promise a wait time before current operating evidence exists.', 'No marketplace or local barbershop directory is included.'],
        ],
        'salons' => [
            'label' => 'Salons',
            'seo_title' => 'Salon booking and business management software | ClipperDesk',
            'title' => 'Salon software that carries multi-service work through the day',
            'description' => 'Coordinate service timing, staff handoffs, client preferences, booking policy and checkout without splitting the visit into disconnected records.',
            'image' => '/images/marketing/industries/home-salon-hero.webp',
            'image_alt' => 'A stylist consulting with a client in a polished modern salon',
            'accent' => 'coral',
            'fit' => 'ClipperDesk fits appointment-led hair and beauty salons whose services can include different staff, add-ons, processing time and durable client context.',
            'requirements' => ['FR-04', 'FR-05', 'FR-06', 'FR-07', 'FR-09', 'FR-11', 'FR-12', 'FR-14'],
            'challenges' => [
                ['title' => 'One visit can contain more than one service', 'body' => 'Service lines retain their own duration, staff eligibility, processing and cleanup segments inside one Appointment.'],
                ['title' => 'Client context needs the right visibility', 'body' => 'Preferences, formulas, sensitivities, forms and warnings stay authored and permission-aware.'],
                ['title' => 'Changes must preserve what the client saw', 'body' => 'Policy, service and price snapshots keep later configuration edits from rewriting the booked visit.'],
            ],
            'day' => ['Publish qualified services and current availability', 'Carry a multi-line appointment into the team calendar', 'Record protected client context during service', 'Apply the deposit and complete a traceable checkout'],
            'features' => ['online-booking', 'calendar-and-walk-ins', 'client-management'],
            'limits' => ['Live deposits remain subject to appointment-payment provider approval.', 'Memberships, packages, loyalty and automated marketing campaigns are not Phase 1.'],
        ],
        'independent-stylists' => [
            'label' => 'Independent stylists',
            'seo_title' => 'Independent stylist booking software | ClipperDesk',
            'title' => 'A simpler operating system for an independent stylist',
            'description' => 'Move from guided setup to booking, the working calendar, client history and checkout without needing a separate admin team.',
            'image' => '/images/marketing/industries/independent-stylist.webp',
            'image_alt' => 'An independent stylist serving a client in a refined one-chair studio',
            'accent' => 'amber',
            'fit' => 'ClipperDesk fits an independent professional who owns the Business and performs the work, while keeping the same permissions and history ready for a future team.',
            'requirements' => ['FR-01', 'FR-02', 'FR-04', 'FR-05', 'FR-09', 'FR-11', 'FR-14', 'FR-18'],
            'challenges' => [
                ['title' => 'Setup needs to show what is truly missing', 'body' => 'Readiness names blocking details, hours, services, availability and policy instead of hiding them behind a percentage.'],
                ['title' => 'The calendar should not require constant reconciliation', 'body' => 'Public and owner-created bookings use the same staff and resource capacity checks.'],
                ['title' => 'A small business still needs explainable history', 'body' => 'Receipts, payments, client visits and reports remain linked without deleting corrections.'],
            ],
            'day' => ['Complete guided readiness and preview the booking page', 'Share the Business-specific booking link', 'Work from one calendar and client record', 'Close the Sale and review the local-day totals'],
            'features' => ['online-booking', 'client-management', 'checkout-and-reporting'],
            'limits' => ['ClipperDesk does not provide a marketing marketplace or guarantee new client demand.', 'The launch profile is web-first; there is no native mobile app.'],
        ],
        'spas' => [
            'label' => 'Spa & sauna',
            'seo_title' => 'Spa and sauna scheduling software | ClipperDesk',
            'title' => 'Spa scheduling that reserves the room as well as the practitioner',
            'description' => 'Coordinate qualified staff, rooms or equipment, multi-segment treatments and consultation evidence with explicit limits.',
            'image' => '/images/marketing/industries/spa-sauna.webp',
            'image_alt' => 'A spa practitioner welcoming a guest in a modern spa and sauna setting',
            'accent' => 'amber',
            'fit' => 'ClipperDesk fits small non-medical spas that need appointment and physical-resource capacity to be committed together.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-07', 'FR-11', 'FR-12'],
            'challenges' => [
                ['title' => 'A free practitioner is not enough', 'body' => 'Configured rooms or equipment can have quantities, opening hours and maintenance that participate in the same capacity decision.'],
                ['title' => 'Treatments may include active and processing time', 'body' => 'Service segments can release or change provider responsibility while keeping the complete visit atomic.'],
                ['title' => 'Consultation evidence must not drift', 'body' => 'Published form wording and submitted answers remain frozen to the appointment and template version.'],
            ],
            'day' => ['Resolve current treatment duration and required resources', 'Offer only capacity that fits staff and the room', 'Collect a versioned pre-appointment form when configured', 'Preserve the visit, submission and checkout context together'],
            'features' => ['online-booking', 'calendar-and-walk-ins', 'client-management'],
            'limits' => ['ClipperDesk does not claim HIPAA, medical-device or healthcare regulatory compliance.', 'Complex medical workflows, classes and facility-wide resource optimisation are not Phase 1.'],
        ],
        'nail-salons' => [
            'label' => 'Nail salons',
            'seo_title' => 'Nail salon booking and scheduling software | ClipperDesk',
            'title' => 'Nail salon software for a beautifully coordinated appointment book',
            'description' => 'Keep technicians, manicure stations, service timing, client preferences and checkout moving in one polished day.',
            'image' => '/images/marketing/industries/nail-salon.webp',
            'image_alt' => 'A nail technician serving a client at a bright contemporary nail bar',
            'accent' => 'coral',
            'fit' => 'ClipperDesk fits nail studios that run appointment-led services across several technicians and stations, from focused independents to busy shared front desks.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-09', 'FR-11', 'FR-14'],
            'challenges' => [
                ['title' => 'The right technician and station must be free', 'body' => 'Availability can consider service eligibility, staff time and configured physical resources before offering the slot.'],
                ['title' => 'Small timing changes ripple through the day', 'body' => 'Service duration, add-ons, cleanup and appointment changes stay visible in the same working calendar.'],
                ['title' => 'Preferences make repeat visits personal', 'body' => 'Useful colour, style and service context can stay with the client record under the right permissions.'],
            ],
            'day' => ['Publish services with accurate timing and technician eligibility', 'Book against the same staff and station capacity the team sees', 'Keep useful client preferences with the visit', 'Complete checkout and carry the service into history'],
            'features' => ['online-booking', 'calendar-and-walk-ins', 'client-management'],
            'limits' => ['ClipperDesk does not include a consumer marketplace or guarantee new bookings.', 'Memberships, packages, loyalty and automated campaigns are outside the current release.'],
        ],
        'medspas' => [
            'label' => 'Medspas',
            'seo_title' => 'Medspa scheduling and business software | ClipperDesk',
            'title' => 'Medspa scheduling and client operations—with clinical boundaries kept clear',
            'description' => 'Coordinate appointments, rooms, practitioner availability, intake forms and payments for non-clinical business operations.',
            'image' => '/images/marketing/industries/medspa.webp',
            'image_alt' => 'A skincare professional consulting with a client in a contemporary medspa',
            'accent' => 'cobalt',
            'fit' => 'ClipperDesk can support the scheduling and commercial side of a medspa where the Business has separately approved clinical, consent, privacy and regulatory systems.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-09', 'FR-11', 'FR-12', 'FR-14'],
            'challenges' => [
                ['title' => 'Practitioner and room capacity must agree', 'body' => 'Configured eligibility and physical resources participate in the same availability decision.'],
                ['title' => 'Intake wording needs a version', 'body' => 'Published forms and submitted answers remain tied to the version used for that appointment.'],
                ['title' => 'Business history still needs traceability', 'body' => 'Appointments, tenders, receipts and corrections remain linked without rewriting earlier evidence.'],
            ],
            'day' => ['Publish only approved non-clinical booking choices', 'Reserve practitioner and room capacity together', 'Collect configured business intake before the visit', 'Close the commercial visit with traceable payment history'],
            'features' => ['online-booking', 'client-management', 'checkout-and-reporting'],
            'limits' => ['ClipperDesk is not an electronic medical record system and makes no HIPAA or healthcare-compliance claim.', 'Clinical charting, prescribing, medical-device workflows and treatment-outcome tracking are not supported.'],
        ],
        'massage' => [
            'label' => 'Massage',
            'seo_title' => 'Massage studio booking software | ClipperDesk',
            'title' => 'Massage studio software that protects practitioner time and room capacity',
            'description' => 'Bring online booking, practitioner schedules, treatment rooms, client preferences and checkout into one calm flow.',
            'image' => '/images/marketing/industries/massage.webp',
            'image_alt' => 'A massage therapist preparing a calm modern treatment room for a client',
            'accent' => 'amber',
            'fit' => 'ClipperDesk fits independent massage practitioners and multi-room studios whose bookable time depends on both qualified people and treatment spaces.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-07', 'FR-09', 'FR-11', 'FR-14'],
            'challenges' => [
                ['title' => 'A practitioner and room are booked together', 'body' => 'Availability checks both staff and configured treatment-room capacity before the time is confirmed.'],
                ['title' => 'Turnover time is real working time', 'body' => 'Cleanup and other service segments can be represented instead of squeezing the next appointment into an impossible gap.'],
                ['title' => 'Returning clients expect context', 'body' => 'Preferences and service history can follow the client without exposing secure records publicly.'],
            ],
            'day' => ['Offer the current service and practitioner choices', 'Hold the room and practitioner for the selected time', 'Keep useful client preferences in context', 'Check out and review the local-day totals'],
            'features' => ['online-booking', 'calendar-and-walk-ins', 'client-management'],
            'limits' => ['ClipperDesk does not provide clinical notes, diagnosis or healthcare compliance.', 'Classes, memberships and complex facility optimisation are outside the current release.'],
        ],
        'fitness-recovery' => [
            'label' => 'Fitness & recovery',
            'seo_title' => 'Fitness and recovery scheduling software | ClipperDesk',
            'title' => 'Fitness and recovery scheduling for coached, appointment-led sessions',
            'description' => 'Coordinate coaches, rooms, recovery equipment, client bookings and payments across a busy studio day.',
            'image' => '/images/marketing/industries/fitness-recovery.webp',
            'image_alt' => 'A coach guiding a client in a modern fitness and recovery studio',
            'accent' => 'lime',
            'fit' => 'ClipperDesk fits appointment-led personal training and recovery studios where sessions need a qualified professional, a space or piece of equipment, and a clear client record.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-09', 'FR-11', 'FR-14', 'FR-18'],
            'challenges' => [
                ['title' => 'Coach, room and equipment capacity collide', 'body' => 'The same availability model can account for qualified staff and configured physical resources.'],
                ['title' => 'Session changes affect the whole floor', 'body' => 'Moves, cancellations, blocks and operational exceptions remain explicit in the calendar.'],
                ['title' => 'Owners need a clean commercial trail', 'body' => 'Completed sessions, tenders and local-day reports stay connected to their source records.'],
            ],
            'day' => ['Publish appointment-led sessions with accurate duration', 'Reserve coach and required recovery capacity', 'Run the studio from one working calendar', 'Close completed sessions and review the day'],
            'features' => ['calendar-and-walk-ins', 'online-booking', 'checkout-and-reporting'],
            'limits' => ['Recurring classes, course programming and membership billing are not supported in the current release.', 'ClipperDesk does not provide clinical recovery plans or health-outcome tracking.'],
        ],
        'physical-therapy' => [
            'label' => 'Physical therapy',
            'seo_title' => 'Physical therapy scheduling software | ClipperDesk',
            'title' => 'Physical therapy scheduling for the non-clinical side of the practice',
            'description' => 'Coordinate appointment capacity, rooms, practitioners, reminders and payments while keeping clinical systems separate.',
            'image' => '/images/marketing/industries/physical-therapy.webp',
            'image_alt' => 'A physical therapist guiding a client through a supervised mobility exercise',
            'accent' => 'lime',
            'fit' => 'ClipperDesk may support appointment and business operations for a physical therapy practice that uses separate approved systems for clinical records and regulated care.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-09', 'FR-11', 'FR-13', 'FR-14'],
            'challenges' => [
                ['title' => 'Practitioner time and treatment space both matter', 'body' => 'Availability can coordinate eligible staff and configured room or equipment capacity.'],
                ['title' => 'Every schedule change needs context', 'body' => 'Rescheduling, cancellation and operational exceptions remain explicit rather than silently editing time.'],
                ['title' => 'Commercial records must stay explainable', 'body' => 'Receipts, payments, adjustments and reports retain links to the completed service record.'],
            ],
            'day' => ['Publish approved appointment types and availability', 'Reserve the practitioner and required room together', 'Send operational reminders through configured providers', 'Record payment and preserve the commercial history'],
            'features' => ['online-booking', 'calendar-and-walk-ins', 'checkout-and-reporting'],
            'limits' => ['ClipperDesk is not an EMR/EHR and makes no HIPAA or healthcare regulatory claim.', 'Diagnosis, clinical documentation, insurance claims and treatment outcomes are not supported.'],
        ],
        'health-practices' => [
            'label' => 'Health practices',
            'seo_title' => 'Health practice scheduling software | ClipperDesk',
            'title' => 'Appointment and business software for independent health practices',
            'description' => 'Organise practitioner calendars, client-facing booking, business forms and payment records without pretending to replace clinical systems.',
            'image' => '/images/marketing/industries/health-practice.webp',
            'image_alt' => 'An independent practitioner consulting with a client in a welcoming modern practice',
            'accent' => 'cobalt',
            'fit' => 'ClipperDesk can fit appointment-led allied-health and wellness practices for non-clinical operations where regulated records and care remain in separately approved systems.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-09', 'FR-11', 'FR-12', 'FR-14'],
            'challenges' => [
                ['title' => 'The booking path needs accurate practitioner rules', 'body' => 'Published services resolve current eligibility, duration, hours and capacity before a time is offered.'],
                ['title' => 'Forms need stable wording', 'body' => 'Versioned business forms keep the submitted response tied to the wording the client actually saw.'],
                ['title' => 'Sensitive context needs boundaries', 'body' => 'Permissions can narrow access, while clinical and regulated records remain outside ClipperDesk.'],
            ],
            'day' => ['Configure approved appointment types and practitioners', 'Publish availability through the Business booking page', 'Collect only the configured non-clinical context', 'Complete payment and retain an auditable business record'],
            'features' => ['online-booking', 'client-management', 'checkout-and-reporting'],
            'limits' => ['ClipperDesk does not provide diagnosis, clinical notes, prescriptions, insurance billing or EMR/EHR capability.', 'Healthcare compliance, retention and consent suitability require independent review before use.'],
        ],
        'tattoo-piercing' => [
            'label' => 'Tattooing & piercing',
            'seo_title' => 'Tattoo and piercing studio software | ClipperDesk',
            'title' => 'Tattoo and piercing studio software for consultations, sessions and the chair plan',
            'description' => 'Coordinate artists, stations, consultation forms, appointment changes, deposits and checkout in one studio workflow.',
            'image' => '/images/marketing/industries/tattoo-piercing.webp',
            'image_alt' => 'A tattoo artist preparing a stencil with a client in a clean contemporary studio',
            'accent' => 'coral',
            'fit' => 'ClipperDesk fits appointment-led tattoo and piercing studios that need explicit artist eligibility, station capacity, versioned forms and traceable payment history.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-09', 'FR-11', 'FR-12', 'FR-14'],
            'challenges' => [
                ['title' => 'Consultations and sessions need different timing', 'body' => 'Each service can carry its real duration, staff eligibility and resource requirements into availability.'],
                ['title' => 'Consent wording must not drift', 'body' => 'Published forms and submitted answers remain frozen to their exact template version.'],
                ['title' => 'Deposits and final balances need one trail', 'body' => 'Configured deposit evidence can carry into checkout without erasing later adjustments.'],
            ],
            'day' => ['Publish consultation and session types with artist eligibility', 'Reserve the artist and configured station capacity', 'Collect the current business form when required', 'Apply deposit evidence and complete the final checkout'],
            'features' => ['online-booking', 'client-management', 'checkout-and-reporting'],
            'limits' => ['Local licensing, age verification, consent and aftercare obligations require independent legal and operational review.', 'Portfolio galleries, marketplace discovery and automated marketing are not supported in the current release.'],
        ],
        'pet-grooming' => [
            'label' => 'Pet grooming',
            'seo_title' => 'Pet grooming booking and scheduling software | ClipperDesk',
            'title' => 'Pet grooming software for busy tables, groomers and repeat visits',
            'description' => 'Coordinate service timing, groomer availability, stations, client contact, pet context and checkout across the day.',
            'image' => '/images/marketing/industries/pet-grooming.webp',
            'image_alt' => 'A professional groomer brushing a dog in a bright modern pet grooming studio',
            'accent' => 'yellow',
            'fit' => 'ClipperDesk fits appointment-led grooming studios that can represent each visit as a service booking tied to the human client and useful authored notes.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-08', 'FR-09', 'FR-11', 'FR-14'],
            'challenges' => [
                ['title' => 'Service time changes by pet and coat', 'body' => 'Accurate service definitions and authored notes help the team plan without pretending every appointment is identical.'],
                ['title' => 'Groomer and station capacity must match', 'body' => 'Configured staff eligibility and physical resources can participate in the same booking decision.'],
                ['title' => 'The front desk needs a clear handoff', 'body' => 'Booking context, notes, status and checkout stay linked through the visit.'],
            ],
            'day' => ['Publish grooming services with realistic timing', 'Reserve an eligible groomer and configured station', 'Keep pet-related service context in authored notes', 'Check out and carry the visit into the client history'],
            'features' => ['online-booking', 'calendar-and-walk-ins', 'client-management'],
            'limits' => ['The current client model is person-led and does not provide a dedicated multi-pet medical or vaccination record.', 'Veterinary charting, kennelling and route-based mobile grooming are not supported.'],
        ],
        'tanning-studios' => [
            'label' => 'Tanning studios',
            'seo_title' => 'Tanning studio booking software | ClipperDesk',
            'title' => 'Tanning studio software for rooms, sessions and a polished client journey',
            'description' => 'Coordinate room capacity, staff, client booking, operational forms and checkout with clear limits.',
            'image' => '/images/marketing/industries/tanning-studio.webp',
            'image_alt' => 'A staff member welcoming a client into a modern tanning studio',
            'accent' => 'amber',
            'fit' => 'ClipperDesk fits appointment-led tanning studios that need staff and room capacity to stay aligned with client-facing booking and payment history.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-09', 'FR-11', 'FR-12', 'FR-14'],
            'challenges' => [
                ['title' => 'Room capacity defines the appointment book', 'body' => 'Configured rooms or equipment participate in availability alongside staff and operating hours.'],
                ['title' => 'Client-facing information needs a stable version', 'body' => 'Published forms keep the submitted response associated with the wording presented for that visit.'],
                ['title' => 'Session payments need traceable history', 'body' => 'Completed services, tenders, receipts and corrections stay linked in the commercial record.'],
            ],
            'day' => ['Publish approved services and current room availability', 'Reserve the relevant room and staff context', 'Collect configured business forms before the session', 'Complete checkout and retain the visit history'],
            'features' => ['online-booking', 'client-management', 'checkout-and-reporting'],
            'limits' => ['Health screening, exposure rules, age limits and local regulation require independent review.', 'Memberships, packages and automated recurring billing are not supported in the current release.'],
        ],
    ],
    'use_cases' => [
        'reduce-scheduling-conflicts' => [
            'label' => 'Reduce scheduling conflicts',
            'seo_title' => 'How to reduce scheduling conflicts | ClipperDesk',
            'image' => '/images/marketing/editorial/product-workday.webp',
            'title' => 'Reduce scheduling conflicts by checking the same capacity twice',
            'description' => 'Use one availability model for client booking and front-desk changes, then revalidate staff, service and resource capacity before committing the appointment.',
            'answer' => 'Scheduling conflicts are best reduced by making every booking path use the same working hours, staff eligibility, service duration and resource rules. ClipperDesk searches those rules, places a short capacity hold and checks them again at confirmation; it helps prevent conflicts but cannot eliminate incorrect configuration or real-world disruption.',
            'requirements' => ['FR-03', 'FR-04', 'FR-05', 'FR-06', 'FR-07'],
            'symptoms' => ['A client sees a time the front desk believes is unavailable.', 'A room or piece of equipment is promised to two services.', 'A late edit silently overwrites a newer calendar change.'],
            'practice' => [
                ['title' => 'Write down the real constraints', 'body' => 'Keep location hours, staff working intervals, breaks, service segments, cleanup time and required resource quantities current.'],
                ['title' => 'Use one booking path', 'body' => 'Create public, front-desk and moved appointments through the same availability and capacity commands rather than adjusting calendar timestamps directly.'],
                ['title' => 'Recheck at the decision point', 'body' => 'Treat search results as advisory and validate the selected slot again when it is held and confirmed.'],
                ['title' => 'Review exceptions as operating evidence', 'body' => 'Record late arrivals, overruns, closures and unavailable staff so the team can recover without disguising the original plan.'],
            ],
            'product_steps' => ['Resolve eligible staff and resources without exposing private schedules.', 'Create an expiring capacity hold for the chosen slot.', 'Lock and revalidate the appointment version before commit.', 'Reject stale or conflicting changes with a clear recovery path.'],
            'limitations' => ['Good configuration still matters: outdated hours, eligibility or resource quantities can make otherwise-correct results unhelpful.', 'Unexpected closures and service overruns require an explicit recovery decision; software cannot guarantee a conflict-free day.'],
            'feature' => 'calendar-and-walk-ins',
            'solution' => 'salons',
        ],
        'manage-walk-ins-and-appointments' => [
            'label' => 'Manage walk-ins and appointments',
            'seo_title' => 'Manage walk-ins and appointments together | ClipperDesk',
            'image' => '/images/marketing/industries/barbershop.webp',
            'title' => 'Manage walk-ins without losing sight of booked appointments',
            'description' => 'Capture the queue, explain the estimate and revalidate capacity before a walk-in becomes an appointment on the working calendar.',
            'answer' => 'Booked appointments and walk-ins can share one operating view when the queue remains a request—not a hidden calendar reservation—until staff and time are assigned. ClipperDesk keeps queue evidence beside the calendar and validates capacity when the walk-in is converted.',
            'requirements' => ['FR-06', 'FR-08'],
            'symptoms' => ['A verbal queue estimate competes with the next booked client.', 'The team cannot tell why one walk-in moved ahead of another.', 'Actual waits disappear, leaving future estimates to guess.'],
            'practice' => [
                ['title' => 'Capture the request consistently', 'body' => 'Record arrival, requested service, preferred or any qualified staff, and the client\'s notification choice.'],
                ['title' => 'Explain the queue order', 'body' => 'Use a visible ordering reason and treat estimated start time as changeable operating guidance.'],
                ['title' => 'Check the real calendar before assignment', 'body' => 'Confirm the service still fits around booked work and staff capacity at the moment of conversion.'],
                ['title' => 'Retain the actual outcome', 'body' => 'Keep served, cancelled, no-response and walk-out outcomes plus actual wait evidence for later review.'],
            ],
            'product_steps' => ['Add a walk-in with service and staff preference.', 'Review the evidence-based estimate and queue order.', 'Assign staff and revalidate capacity atomically.', 'Start service and preserve the queue-to-appointment history.'],
            'limitations' => ['A wait estimate is not a promise and should change when current work, staffing or service choice changes.', 'A walk-in cannot override a real staff or resource conflict; a manager may override policy warnings only.'],
            'feature' => 'calendar-and-walk-ins',
            'solution' => 'barbershops',
        ],
        'protect-time-with-deposits' => [
            'label' => 'Protect time with deposits',
            'seo_title' => 'Booking deposits for service businesses | ClipperDesk',
            'image' => '/images/marketing/editorial/pricing-decision.webp',
            'title' => 'Use deposits as one part of a clear booking policy',
            'description' => 'Show the current deposit and cancellation terms before confirmation, preserve the accepted policy version and apply completed payment evidence at checkout.',
            'answer' => 'A deposit can help protect reserved time when the amount, due point, cancellation terms and refund handling are clear. ClipperDesk can calculate and snapshot configured policy, but live collection depends on an approved payment provider and no deposit guarantees attendance.',
            'requirements' => ['FR-09', 'FR-10', 'FR-14'],
            'symptoms' => ['Clients do not see the cancellation terms until after booking.', 'A policy edit appears to change an older appointment.', 'The front desk cannot trace a deposit into the final balance or refund.'],
            'practice' => [
                ['title' => 'Choose a proportionate rule', 'body' => 'Decide which services require a deposit, how it is calculated and what happens after cancellation or no-show, with appropriate legal review.'],
                ['title' => 'Show the terms before consent', 'body' => 'Present the amount and cancellation policy in the booking flow before confirmation rather than relying on a later message.'],
                ['title' => 'Preserve what was accepted', 'body' => 'Snapshot the policy version and deposit requirement so future configuration edits do not rewrite the agreement.'],
                ['title' => 'Reconcile the money', 'body' => 'Link successful, failed, refunded or waived deposit evidence to the appointment and final Sale without deleting corrections.'],
            ],
            'product_steps' => ['Resolve the published policy for the booking context.', 'Display and snapshot the deposit requirement before confirmation.', 'Accept provider callbacks idempotently when live collection is enabled.', 'Apply completed deposit evidence to checkout and record later corrections.'],
            'limitations' => ['Live appointment payment collection is not launch-ready until Stripe provider approval, webhook and settlement certification are complete.', 'ClipperDesk does not guarantee that deposits reduce no-shows or supply legal advice about cancellation terms.'],
            'feature' => 'online-booking',
            'solution' => 'independent-stylists',
        ],
        'keep-client-history-together' => [
            'label' => 'Keep client history together',
            'seo_title' => 'Keep service business client history connected | ClipperDesk',
            'image' => '/images/marketing/industries/spa-sauna.webp',
            'title' => 'Keep useful client history connected to the service record',
            'description' => 'Connect visits, preferences, protected notes, forms, consent, messages and purchases while keeping sensitive context permission-aware.',
            'answer' => 'A useful client history connects service and commerce records without turning every note into public team context. ClipperDesk keeps one Business-owned profile with authored, permission-aware records and conservative matching rather than silently merging similar people.',
            'requirements' => ['FR-11', 'FR-12', 'FR-13', 'FR-14', 'FR-19'],
            'symptoms' => ['Preferences and formulas live in personal notes that the next authorised professional cannot find.', 'Duplicate profiles split visits and receipts across identities.', 'A contact update loses the earlier audit trail or weakens secure links.'],
            'practice' => [
                ['title' => 'Collect only useful context', 'body' => 'Define why each field or note is needed, who can see it and how long it should remain.'],
                ['title' => 'Separate general from protected notes', 'body' => 'Use narrower access for sensitivities, formulas, warnings and consultation evidence instead of sharing everything equally.'],
                ['title' => 'Match and merge conservatively', 'body' => 'Reuse exact normalized identity where safe; review possible duplicates and preview all relationships before merging.'],
                ['title' => 'Preserve requests and changes', 'body' => 'Track consent, contact changes and privacy cases with authorship and deadlines rather than erasing the evidence.'],
            ],
            'product_steps' => ['Open the Business-owned client profile from the appointment.', 'Review visits, forms and protected notes within current permission scope.', 'Carry completed service and Sale context into history.', 'Audit identity changes, merges and privacy-request outcomes.'],
            'limitations' => ['Final destructive deletion and anonymisation remain blocked until OPEN-10 approves the retention schedule and executor.', 'ClipperDesk is not a medical-record system and does not claim healthcare regulatory compliance.'],
            'feature' => 'client-management',
            'solution' => 'spas',
        ],
    ],
    'guides' => [
        'booking-policy-basics' => [
            'seo_title' => 'Booking policy guide for service businesses | ClipperDesk',
            'image' => '/images/marketing/editorial/resources-planning.webp',
            'title' => 'Booking policy basics for a clearer client decision',
            'description' => 'A practical framework for making booking, deposit, cancellation and change terms visible and operable.',
            'topic' => 'Booking policy', 'published_at' => '2026-08-16', 'reviewed_by' => 'ClipperDesk Product and Engineering',
            'intro' => 'A useful booking policy tells clients what is reserved, what may be charged, when changes are allowed and how exceptions are handled. It should match the team’s actual operating process and receive appropriate legal review.',
            'sections' => [
                ['title' => 'Start with the operating decision', 'body' => 'List which services, staff or lead times need special handling. Avoid copying a stricter policy that the team cannot apply consistently.'],
                ['title' => 'Put terms before confirmation', 'body' => 'Show deposit amount, cancellation window and important exceptions before the client confirms—not only in a later reminder.'],
                ['title' => 'Preserve the accepted version', 'body' => 'Keep the policy version and calculation attached to the appointment so a later edit does not rewrite an earlier agreement.'],
                ['title' => 'Design the exception path', 'body' => 'Define who may waive a deposit or policy warning, which reason is recorded and how a refund or checkout correction remains traceable.'],
            ],
            'checklist' => ['Services and circumstances covered', 'Deposit calculation and due point', 'Cancellation/reschedule window', 'Late/no-show handling', 'Refund/waiver authority and reason', 'Client-visible contact or recovery path', 'Legal and operations approval date'],
            'limitation' => 'This guide is general operating guidance, not legal advice. Live deposit collection in ClipperDesk remains provider-qualified.',
            'feature' => 'online-booking',
        ],
        'salon-opening-checklist' => [
            'seo_title' => 'Service business opening checklist | ClipperDesk',
            'image' => '/images/marketing/industries/independent-stylist.webp',
            'title' => 'A service business opening checklist grounded in the working day',
            'description' => 'Prepare the minimum business, location, service, staff and booking rules needed before sharing an online booking link.',
            'topic' => 'Business setup', 'published_at' => '2026-08-16', 'reviewed_by' => 'ClipperDesk Product and Engineering',
            'intro' => 'Opening readiness is clearer when it names each blocking operating fact instead of hiding the work behind a percentage. Complete the facts your calendar and clients depend on first.',
            'sections' => [
                ['title' => 'Define the Business and location day', 'body' => 'Confirm display name, time zone, currency, address/contact context and the local opening intervals that determine bookable time.'],
                ['title' => 'Make services schedulable', 'body' => 'Give each service an accurate duration, price, eligible staff and any processing, cleanup, add-on or physical-resource requirement.'],
                ['title' => 'Make staff availability explicit', 'body' => 'Record each person’s location assignment, working intervals, breaks and service eligibility before relying on public availability.'],
                ['title' => 'Preview before publishing', 'body' => 'Review policy, booking questions and client-facing choices with synthetic bookings, then publish the Business-specific booking route only when the blockers are clear.'],
            ],
            'checklist' => ['Business name, time zone and currency', 'Location details and weekly hours', 'Service duration, price and eligibility', 'Staff assignments, hours and breaks', 'Resource quantities where needed', 'Booking/deposit/cancellation policy', 'Owner preview and readiness review'],
            'limitation' => 'This checklist does not replace tax, employment, licensing, safety, insurance or privacy advice for a specific service business.',
            'feature' => 'calendar-and-walk-ins',
        ],
    ],
];
