<?php

return [
    'terms' => [
        'title' => 'Terms and Conditions',
        'page_title' => 'ClipperDesk Terms and Conditions',
        'summary' => 'The proposed contract for accessing and using ClipperDesk, including account, subscription, salon-client commerce, acceptable-use, data and termination terms.',
        'status' => 'Counsel review draft — not yet effective',
        'version' => '0.2-review',
        'reviewed_at' => '25 August 2026',
        'effective_at' => 'Pending legal and Product approval',
        'owner' => 'Named Indian counsel and Product owner required',
        'file' => 'terms.md',
        'prop' => 'terms',
        'component' => 'TermsOfService',
        'route' => 'terms.show',
        'sections' => [
            ['id' => 'status-and-scope', 'label' => 'Status and scope'],
            ['id' => 'accounts', 'label' => 'Accounts and authority'],
            ['id' => 'business-responsibilities', 'label' => 'Business responsibilities'],
            ['id' => 'billing', 'label' => 'Plans and billing'],
            ['id' => 'salon-payments', 'label' => 'Salon-client payments'],
            ['id' => 'acceptable-use', 'label' => 'Acceptable use'],
            ['id' => 'data-and-privacy', 'label' => 'Data and privacy'],
            ['id' => 'termination', 'label' => 'Termination'],
            ['id' => 'legal-terms', 'label' => 'Legal terms pending approval'],
        ],
        'related' => [
            ['label' => 'Privacy Policy', 'route' => 'policy.show'],
            ['label' => 'Refund Policy', 'route' => 'refund.show'],
            ['label' => 'Security', 'route' => 'marketing.security'],
        ],
    ],
    'privacy' => [
        'title' => 'Privacy Policy',
        'page_title' => 'ClipperDesk Privacy Policy',
        'summary' => 'How ClipperDesk proposes to collect, use, disclose, secure and retain information across the public site, business accounts and salon booking journeys.',
        'status' => 'Privacy and counsel review draft — not yet effective',
        'version' => '0.2-review',
        'reviewed_at' => '25 August 2026',
        'effective_at' => 'Pending Privacy/DPO, legal and Product approval',
        'owner' => 'Named Indian Privacy/DPO, counsel and Product owners required',
        'file' => 'policy.md',
        'prop' => 'policy',
        'component' => 'PrivacyPolicy',
        'route' => 'policy.show',
        'sections' => [
            ['id' => 'status-and-scope', 'label' => 'Status and scope'],
            ['id' => 'our-roles', 'label' => 'Our data roles'],
            ['id' => 'data-we-handle', 'label' => 'Data we handle'],
            ['id' => 'how-we-use-data', 'label' => 'How data is used'],
            ['id' => 'payments', 'label' => 'Payment data'],
            ['id' => 'sharing', 'label' => 'Sharing and providers'],
            ['id' => 'retention', 'label' => 'Retention'],
            ['id' => 'rights', 'label' => 'Choices and rights'],
            ['id' => 'cookies', 'label' => 'Cookies and measurement'],
            ['id' => 'contact', 'label' => 'Contact and unresolved items'],
        ],
        'related' => [
            ['label' => 'Terms and Conditions', 'route' => 'terms.show'],
            ['label' => 'Refund Policy', 'route' => 'refund.show'],
            ['label' => 'Security', 'route' => 'marketing.security'],
        ],
    ],
    'refund' => [
        'title' => 'Refund, Return and Cancellation Policy',
        'page_title' => 'ClipperDesk Refund and Cancellation Policy',
        'summary' => 'The proposed refund and cancellation framework for ClipperDesk subscriptions and, separately, salon-client deposits and payments processed through the platform.',
        'status' => 'Finance, Operations and counsel review draft — not yet effective',
        'version' => '0.1-review',
        'reviewed_at' => '25 August 2026',
        'effective_at' => 'Pending Finance, Operations, legal and Product approval',
        'owner' => 'Named Finance, Operations, Indian counsel and Product owners required',
        'file' => 'refund.md',
        'prop' => 'refund',
        'component' => 'RefundPolicy',
        'route' => 'refund.show',
        'sections' => [
            ['id' => 'status-and-scope', 'label' => 'Status and scope'],
            ['id' => 'subscription-refunds', 'label' => 'ClipperDesk subscriptions'],
            ['id' => 'appointment-refunds', 'label' => 'Appointments and deposits'],
            ['id' => 'eligibility', 'label' => 'Eligibility'],
            ['id' => 'request-process', 'label' => 'How to request'],
            ['id' => 'processing-times', 'label' => 'Processing times'],
            ['id' => 'returns-and-delivery', 'label' => 'Returns and delivery'],
            ['id' => 'disputes', 'label' => 'Disputes and safeguards'],
        ],
        'related' => [
            ['label' => 'Terms and Conditions', 'route' => 'terms.show'],
            ['label' => 'Privacy Policy', 'route' => 'policy.show'],
            ['label' => 'Pricing', 'route' => 'marketing.pricing'],
        ],
    ],
];
